package sqlcgen

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/mbvlabs/andurel/pkg/naming"
)

// fileTemplate emits one Go file per model.
//
// The output references three identifiers the project must provide:
//
//   - storage.Executor / storage.Op* / storage.Execute  (from internal/storage)
//   - db.New() and db.{QueryName}                       (from sqlc-gen-go output)
//   - {Model}Entity and rowTo{Model}Entity              (from the user's models/{snake}.go)
//
// All three are user-controlled; the plugin only emits call sites.
const fileTemplate = `// Code generated by andurel-sqlc-gen. DO NOT EDIT.
// Source: andurel sqlc plugin

package {{ .Package }}

import (
{{- range .Imports }}
	{{ if .Alias }}{{ .Alias }} {{ end }}"{{ .Path }}"
{{- end }}
)

// {{ .BaseType }} is the receiver for hooks and policy methods on {{ .Model }}.
// It is intentionally zero-sized — the user adds methods (CanAccess, BeforeFind,
// AfterCreate, etc.) on this type in models/{{ snake .Model }}.go.
type {{ .BaseType }} struct{}

// {{ .Model }} is the singleton model handle. Call methods on it from controllers:
//   models.{{ .Model }}.Find(ctx, exec, id)
var {{ .Model }} = {{ .BaseType }}{}

{{ range .Methods }}
{{- template "method" dict "Method" . "Outer" $ -}}
{{ end }}

// --- raw helpers (unexported, do not call directly) ---

{{ range .Methods }}
{{- template "rawHelper" dict "Method" . "Outer" $ -}}
{{ end }}
`

const methodTemplate = `
{{- with .Method -}}
func (m {{ $.Outer.BaseType }}) {{ .MethodName }}(ctx context.Context, exec storage.Executor{{ range .Params }}, {{ .Name }} {{ .Type }}{{ end }})
{{- if .IsExec }} error {
	_, err := storage.Execute(ctx, exec, storage.{{ .Op }}, m, func() (struct{}, error) {
		return struct{}{}, raw{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
	})
	return err
}
{{- else if .IsExecRows }} (int64, error) {
	return storage.Execute(ctx, exec, storage.{{ .Op }}, m, func() (int64, error) {
		return raw{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
	})
}
{{- else if .IsMany }} ({{ .ReturnEntity }}, error) {
	return storage.Execute(ctx, exec, storage.{{ .Op }}, m, func() ({{ .ReturnEntity }}, error) {
		rows, err := raw{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
		if err != nil {
			return nil, err
		}
		out := make({{ .ReturnEntity }}, len(rows))
		for i, row := range rows {
			out[i] = {{ $.Outer.RowMapper }}(row)
		}
		return out, nil
	})
}
{{- else }} ({{ .ReturnEntity }}, error) {
	return storage.Execute(ctx, exec, storage.{{ .Op }}, m, func() ({{ .ReturnEntity }}, error) {
		row, err := raw{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
		if err != nil {
			return {{ .ReturnEntity }}{}, err
		}
		return {{ $.Outer.RowMapper }}(row), nil
	})
}
{{- end }}
{{- end }}
`

const rawHelperTemplate = `
{{- with .Method -}}
func raw{{ .RawName }}(ctx context.Context, exec storage.Executor{{ range .Params }}, {{ .Name }} {{ .Type }}{{ end }})
{{- if .IsExec }} error {
	return db.New().{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
}
{{- else if .IsExecRows }} (int64, error) {
	return db.New().{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
}
{{- else if .IsMany }} ([]db.{{ $.Outer.Model }}, error) {
	return db.New().{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
}
{{- else }} (db.{{ $.Outer.Model }}, error) {
	return db.New().{{ .RawName }}(ctx, exec{{ range .CallArgs }}, {{ . }}{{ end }})
}
{{- end }}
{{- end }}
`

// dictFunc is a small helper used to pass multiple values into nested templates.
// text/template doesn't natively support multi-arg invocation, so we wrap them in a map.
func dictFunc(values ...any) (map[string]any, error) {
	if len(values)%2 != 0 {
		return nil, fmt.Errorf("dict requires an even number of arguments")
	}
	out := make(map[string]any, len(values)/2)
	for i := 0; i < len(values); i += 2 {
		key, ok := values[i].(string)
		if !ok {
			return nil, fmt.Errorf("dict key %d must be a string, got %T", i, values[i])
		}
		out[key] = values[i+1]
	}
	return out, nil
}

func renderFile(view fileView) ([]byte, error) {
	tmpl := template.New("file").Funcs(template.FuncMap{
		"dict":  dictFunc,
		"snake": naming.ToSnakeCase,
	})

	if _, err := tmpl.New("method").Parse(methodTemplate); err != nil {
		return nil, fmt.Errorf("parse method template: %w", err)
	}
	if _, err := tmpl.New("rawHelper").Parse(rawHelperTemplate); err != nil {
		return nil, fmt.Errorf("parse rawHelper template: %w", err)
	}
	if _, err := tmpl.Parse(fileTemplate); err != nil {
		return nil, fmt.Errorf("parse file template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}
