ARG GO_VERSION={{.GoVersion}}
{{- if eq .CSSFramework "tailwind"}}
FROM debian:bookworm-slim AS css-builder

WORKDIR /usr/src/app

COPY bin/tailwindcli ./bin/tailwindcli
COPY css ./css
COPY views ./views

RUN ./bin/tailwindcli -i ./css/base.css -o ./assets/css/style.css --minify
{{- end}}

FROM golang:${GO_VERSION}-bookworm AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
{{- if eq .CSSFramework "tailwind"}}
COPY --from=css-builder /usr/src/app/assets/css/style.css ./assets/css/style.css
{{- end}}

RUN CGO_ENABLED=0 GOOS=linux go build -v -o /run-app ./cmd/app

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /run-app /usr/local/bin/run-app

WORKDIR /app

EXPOSE 8080

CMD ["run-app"]
