package cli

var commandMetaSpecs = map[string]CommandMeta{
	"andurel": {
		Summary:   "Andurel CLI for humans and agents",
		WhenToUse: []string{"Discover commands, then run a specific subcommand."},
		WhenNotToUse: []string{
			"Do not guess generator names; run andurel commands --json first.",
		},
		Examples: []string{
			"andurel commands --json",
			"andurel --help",
			"andurel new myapp",
		},
	},
	"andurel new": {
		Summary:         "Stand up a new Andurel project",
		Args:            "[project-name]",
		WhenToUse:       []string{"Create a new application directory from the current scaffold."},
		WhenNotToUse:    []string{"Do not run inside an existing Andurel project."},
		Next:            []string{"cd <project>", "andurel tool sync", "andurel doctor --json"},
		Examples:        []string{"andurel new myapp", "andurel new myapp --ui vue/pnpm", "andurel new myapp --dry-run --json"},
		Mutating:        true,
		SupportsDryRun:  true,
		RequiresProject: false,
	},
	"andurel generate": {
		Summary:         "Create application-owned code",
		WhenToUse:       []string{"Create migrations, models, controllers, scaffolds, jobs, emails, or SQL query files."},
		WhenNotToUse:    []string{"Use inspect commands to list existing files.", "Use andurel sync to refresh derived files."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel generate --help", "andurel generate scaffold Post --dry-run --json", "andurel generate migration create_posts"},
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel sync": {
		Summary:         "Refresh derived files from a source of truth",
		WhenToUse:       []string{"Regenerate *_templ.go, narsilc output, Inertia routes/payloads, emails, or factories."},
		WhenNotToUse:    []string{"Creating application-owned files is andurel generate.", "Downloading binaries is andurel tool sync."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel sync --help", "andurel sync queries", "andurel sync routes --json"},
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel inspect": {
		Summary:         "Read-only project shape",
		WhenToUse:       []string{"List metadata, routes, models, and other source files without writing."},
		WhenNotToUse:    []string{"Refreshing derived files is andurel sync."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect --help", "andurel inspect project --json"},
		RequiresProject: true,
	},
	"andurel generate model": {
		Summary:          "Generate or update a model from a SQL migration",
		Args:             "NAME",
		WhenToUse:        []string{"Create models/NAME.go from an existing table migration.", "Pass --update after a migration changes columns."},
		WhenNotToUse:     []string{"Do not invent columns by hand; write a migration first."},
		Prerequisites:    []string{"Andurel project root", "Matching migration in migrations/"},
		Next:             []string{"andurel sync factory NAME --check", "andurel inspect models --json"},
		Examples:         []string{"andurel generate model Post --dry-run --json", "andurel generate model Post --update --yes"},
		Mutating:         true,
		RequiresProject:  true,
		SupportsDryRun:   true,
		Prompts:          true,
		InteractiveFlags: []string{"--primary-key", "--yes"},
	},
	"andurel sync factory": {
		Summary:         "Sync one model factory from the model Entity",
		Args:            "NAME",
		WhenToUse:       []string{"Refresh models/factories after the Entity changed."},
		WhenNotToUse:    []string{"Do not use this to author custom factory helpers; keep those outside generated blocks."},
		Prerequisites:   []string{"Andurel project root", "Existing model Entity"},
		Next:            []string{"andurel sync factories --check"},
		Examples:        []string{"andurel sync factory User --check --json", "andurel sync factory User --sync"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel sync factories": {
		Summary:         "Check or sync every model factory",
		WhenToUse:       []string{"CI drift check or repo-wide factory refresh."},
		WhenNotToUse:    []string{"Requires --check or --sync; do not run without one of those flags."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel sync factories --check --json", "andurel sync factories --sync"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel sync views": {
		Summary:         "Generate Go from Templ templates",
		WhenToUse:       []string{"Refresh *_templ.go after editing .templ files."},
		WhenNotToUse:    []string{"Do not confuse with andurel inspect views, which only lists templates."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel doctor --json"},
		Examples:        []string{"andurel sync views"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel generate query": {
		Summary:         "Create a narsilc SQL query file",
		Args:            "NAME",
		WhenToUse:       []string{"Add a new models/queries/*.sql file for typed persistence."},
		WhenNotToUse:    []string{"Do not use this to compile SQL; that is andurel sync queries."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel sync queries"},
		Examples:        []string{"andurel generate query UserReport --dry-run --json", "andurel generate query UserReport --table users"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel sync queries": {
		Summary:         "Compile narsilc SQL into Go",
		WhenToUse:       []string{"After adding or editing annotated SQL in models/queries."},
		WhenNotToUse:    []string{"No-op when there are no annotated query files.", "Do not confuse with generate query."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel doctor --json"},
		Examples:        []string{"andurel sync queries --json"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel generate controller": {
		Summary:         "Generate a controller, views, and routes",
		Args:            "[ns/]NAME [actions...]",
		WhenToUse:       []string{"Add an HTTP resource when the model already exists."},
		WhenNotToUse:    []string{"Use generate scaffold to also create the model.", "Use --api for JSON; generate otherwise follows the project UI."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel sync routes", "andurel sync payloads", "andurel inspect routes --json"},
		Examples:        []string{"andurel generate controller Widget index show --dry-run --json", "andurel generate controller admin/Widget"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel generate scaffold": {
		Summary:          "Generate a model, controller, views, and routes",
		Args:             "[ns/]NAME",
		WhenToUse:        []string{"Add a full resource from an existing table migration."},
		WhenNotToUse:     []string{"Use generate model or generate controller when you only need one layer."},
		Prerequisites:    []string{"Andurel project root", "Matching migration in migrations/"},
		Next:             []string{"andurel sync routes", "andurel sync payloads", "andurel doctor --json"},
		Examples:         []string{"andurel generate scaffold Post --dry-run --json", "andurel generate scaffold admin/Widget"},
		Mutating:         true,
		RequiresProject:  true,
		SupportsDryRun:   true,
		Prompts:          true,
		InteractiveFlags: []string{"--primary-key"},
	},
	"andurel generate job": {
		Summary:         "Generate a background job and worker",
		Args:            "NAME",
		WhenToUse:       []string{"Add a River job plus worker registration."},
		WhenNotToUse:    []string{"Do not confuse with andurel inspect jobs, which only lists files."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel inspect jobs --json"},
		Examples:        []string{"andurel generate job SendWelcomeEmail --dry-run --json"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel generate email": {
		Summary:         "Author a new email template",
		Args:            "NAME",
		WhenToUse:       []string{"Create email/NAME.templ for transactional or marketing mail."},
		WhenNotToUse:    []string{"Compiling Tailwind in emails is andurel sync email."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel sync email"},
		Examples:        []string{"andurel generate email WelcomeEmail --dry-run --json"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel sync routes": {
		Summary:         "Write TypeScript route helpers for Inertia",
		WhenToUse:       []string{"After adding or changing Inertia routes in router/routes."},
		WhenNotToUse:    []string{"Do not confuse with andurel inspect routes, which only lists the manifest.", "Templ projects do not use this command."},
		Prerequisites:   []string{"Andurel project root", "Inertia adapter in andurel.lock"},
		Next:            []string{"andurel sync payloads"},
		Examples:        []string{"andurel sync routes --json"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel sync payloads": {
		Summary:         "Write TypeScript payload types for Inertia",
		WhenToUse:       []string{"After changing Inertia controller payload or Bind structs."},
		WhenNotToUse:    []string{"Templ projects do not use this command."},
		Prerequisites:   []string{"Andurel project root", "Inertia adapter in andurel.lock"},
		Examples:        []string{"andurel sync payloads --json"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel fmt": {
		Summary:         "Format Go and Templ source files",
		WhenToUse:       []string{"Normalize formatting before commit.", "Use --check in CI."},
		WhenNotToUse:    []string{"This is not go vet; use andurel doctor for diagnostics."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel fmt", "andurel fmt --check"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db": {
		Summary:         "Database lifecycle and migrations",
		WhenToUse:       []string{"Create, drop, migrate, or seed the project database."},
		WhenNotToUse:    []string{"Use andurel db console for an interactive SQL shell."},
		Prerequisites:   []string{"Andurel project root", ".env database variables"},
		Examples:        []string{"andurel db --help", "andurel db migrate up"},
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db create": {
		Summary:         "Create the configured database",
		WhenToUse:       []string{"First-time setup when the database does not exist."},
		WhenNotToUse:    []string{"No-op if the database already exists."},
		Prerequisites:   []string{"Andurel project root", ".env database variables"},
		Next:            []string{"andurel db migrate up"},
		Examples:        []string{"andurel db create"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db drop": {
		Summary:          "Drop the configured database",
		WhenToUse:        []string{"Destroy the project database on purpose."},
		WhenNotToUse:     []string{"Do not run against shared or production databases."},
		Prerequisites:    []string{"Andurel project root", ".env database variables"},
		Examples:         []string{"andurel db drop", "andurel db drop --force"},
		Mutating:         true,
		Destructive:      true,
		RequiresProject:  true,
		SkipDryRunCheck:  true,
		Prompts:          true,
		InteractiveFlags: []string{"--force"},
	},
	"andurel db nuke": {
		Summary:          "Drop and recreate the configured database",
		WhenToUse:        []string{"Reset to an empty database without running migrations."},
		WhenNotToUse:     []string{"Use database rebuild to also migrate and seed."},
		Prerequisites:    []string{"Andurel project root", ".env database variables"},
		Next:             []string{"andurel db migrate up"},
		Examples:         []string{"andurel db nuke --force"},
		Mutating:         true,
		Destructive:      true,
		RequiresProject:  true,
		SkipDryRunCheck:  true,
		Prompts:          true,
		InteractiveFlags: []string{"--force"},
	},
	"andurel db rebuild": {
		Summary:          "Drop, recreate, migrate, and seed the database",
		WhenToUse:        []string{"Full local database reset."},
		WhenNotToUse:     []string{"Do not run against shared or production databases."},
		Prerequisites:    []string{"Andurel project root", ".env database variables"},
		Examples:         []string{"andurel db rebuild --force"},
		Mutating:         true,
		Destructive:      true,
		RequiresProject:  true,
		SkipDryRunCheck:  true,
		Prompts:          true,
		InteractiveFlags: []string{"--force"},
	},
	"andurel db seed": {
		Summary:         "Run database seeds",
		Args:            "[name]",
		WhenToUse:       []string{"Load named seed sets after migrations."},
		WhenNotToUse:    []string{"Use --list to discover names before running."},
		Prerequisites:   []string{"Andurel project root", "cmd/seeds"},
		Examples:        []string{"andurel db seed --list --json", "andurel db seed development"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate": {
		Summary:         "Apply, roll back, and inspect SQL migrations",
		WhenToUse:       []string{"Manage goose migrations in migrations/."},
		WhenNotToUse:    []string{"Creating a migration file is andurel generate migration."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel db migrate status", "andurel db migrate up"},
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel generate migration": {
		Summary:         "Create a new SQL migration file",
		Args:            "[name]",
		WhenToUse:       []string{"Add a schema change as SQL in migrations/."},
		WhenNotToUse:    []string{"This does not apply the migration; run migrate up next."},
		Prerequisites:   []string{"Andurel project root"},
		Next:            []string{"andurel db migrate up", "andurel generate model NAME"},
		Examples:        []string{"andurel generate migration create_posts"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate up": {
		Summary:         "Apply pending SQL migrations",
		WhenToUse:       []string{"Bring the database schema up to date."},
		Prerequisites:   []string{"Andurel project root", "bin/goose", ".env database variables"},
		Examples:        []string{"andurel db migrate up"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate down": {
		Summary:         "Roll back the most recent migration",
		WhenToUse:       []string{"Undo the last applied migration."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate down"},
		Mutating:        true,
		Destructive:     true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate status": {
		Summary:         "Show migration status",
		WhenToUse:       []string{"Inspect which migrations are applied."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate status"},
		RequiresProject: true,
	},
	"andurel db migrate fix": {
		Summary:         "Re-number migrations to fix gaps",
		WhenToUse:       []string{"Close gaps in sequential goose versions."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate fix"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate reset": {
		Summary:         "Roll back all migrations and re-apply them",
		WhenToUse:       []string{"Replay every migration against the current database."},
		WhenNotToUse:    []string{"Use database rebuild to also drop and recreate the database."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate reset"},
		Mutating:        true,
		Destructive:     true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate up-to": {
		Summary:         "Apply migrations up to a version",
		Args:            "[version]",
		WhenToUse:       []string{"Migrate forward only to a specific goose version."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate up-to 20250101120000"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db migrate down-to": {
		Summary:         "Roll back migrations down to a version",
		Args:            "[version]",
		WhenToUse:       []string{"Migrate backward to a specific goose version."},
		Prerequisites:   []string{"Andurel project root", "bin/goose"},
		Examples:        []string{"andurel db migrate down-to 20250101120000"},
		Mutating:        true,
		Destructive:     true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel sync email": {
		Summary:         "Compile Tailwind classes in email templates",
		WhenToUse:       []string{"After editing email/*.templ, css/email.css, or css/theme.css."},
		WhenNotToUse:    []string{"Does not modify authored .templ files."},
		Prerequisites:   []string{"Andurel project root", "email/ and css/email.css"},
		Examples:        []string{"andurel sync email"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel run": {
		Summary:         "Start the development server",
		WhenToUse:       []string{"Local development with auto-reload."},
		WhenNotToUse:    []string{"Agents should not use run to finish a generation task.", "This is a long-running process, not JSON."},
		Prerequisites:   []string{"Andurel project root", "bin/shadowfax"},
		Examples:        []string{"andurel run"},
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel db console": {
		Summary:         "Open an interactive database console",
		WhenToUse:       []string{"Inspect or query the project database with usql."},
		WhenNotToUse:    []string{"Not for applying migrations; use database migrate."},
		Prerequisites:   []string{"Andurel project root", ".env", "bin/usql"},
		Examples:        []string{"andurel db console"},
		RequiresProject: true,
	},
	"andurel tool": {
		Summary:         "Manage project tools and binaries",
		WhenToUse:       []string{"List, pin, download, or launch lockfile tools."},
		WhenNotToUse:    []string{"Application code generation is under generate, not tool."},
		Prerequisites:   []string{"Andurel project root", "andurel.lock"},
		Examples:        []string{"andurel tool --help", "andurel tool list --json", "andurel tool sync"},
		RequiresProject: true,
	},
	"andurel tool sync": {
		Summary:         "Download pinned binaries from andurel.lock",
		WhenToUse:       []string{"After clone, lockfile changes, or missing bin/ tools."},
		WhenNotToUse:    []string{"This does not refresh derived app files such as routes.ts."},
		Prerequisites:   []string{"Andurel project root", "andurel.lock"},
		Examples:        []string{"andurel tool sync"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel tool list": {
		Summary:         "List project tool status",
		WhenToUse:       []string{"See which lockfile tools are installed in bin/."},
		Prerequisites:   []string{"Andurel project root", "andurel.lock"},
		Examples:        []string{"andurel tool list --json"},
		RequiresProject: true,
	},
	"andurel tool set-version": {
		Summary:         "Pin a tool version in andurel.lock and sync it",
		Args:            "<tool> <version>",
		WhenToUse:       []string{"Change a managed binary version."},
		Prerequisites:   []string{"Andurel project root", "andurel.lock"},
		Next:            []string{"andurel tool list --json"},
		Examples:        []string{"andurel tool set-version templ 0.3.977"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel tool dblab": {
		Summary:         "Open the dblab database UI",
		WhenToUse:       []string{"Interactive database browsing."},
		Prerequisites:   []string{"Andurel project root", "bin/dblab", ".env"},
		Examples:        []string{"andurel tool dblab"},
		RequiresProject: true,
	},
	"andurel tool mailpit": {
		Summary:         "Start Mailpit for local email capture",
		WhenToUse:       []string{"Inspect emails sent during local development."},
		Prerequisites:   []string{"Andurel project root", "bin/mailpit"},
		Examples:        []string{"andurel tool mailpit"},
		RequiresProject: true,
	},
	"andurel build": {
		Summary:         "Build the application for production",
		WhenToUse:       []string{"Create the production binary and compiled assets."},
		WhenNotToUse:    []string{"Use andurel run for local development."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel build", "andurel build --version 1.2.3"},
		Mutating:        true,
		RequiresProject: true,
		SkipDryRunCheck: true,
	},
	"andurel upgrade": {
		Summary:         "Upgrade framework-owned files to this CLI version",
		WhenToUse:       []string{"After installing a newer Andurel CLI, refresh managed files."},
		WhenNotToUse:    []string{"Commit first. Use packages update to bump pkg modules without a framework upgrade."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel upgrade --dry-run --json", "andurel upgrade"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel packages": {
		Summary:       "List or update Andurel packages in go.mod",
		WhenToUse:     []string{"List or bump github.com/mbvlabs/andurel/pkg/* modules already required in go.mod."},
		WhenNotToUse:  []string{"Framework file upgrades are andurel upgrade."},
		Prerequisites: []string{"Andurel project root"},
		Examples: []string{
			"andurel packages --help",
			"andurel packages list --json",
			"andurel packages update --dry-run",
		},
		RequiresProject: true,
	},
	"andurel packages list": {
		Summary:         "List Andurel package versions in go.mod",
		WhenToUse:       []string{"Compare required pkg modules against @latest."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel packages list --json"},
		RequiresProject: true,
	},
	"andurel packages update": {
		Summary:         "Update Andurel packages in go.mod to latest",
		Args:            "[packages...]",
		WhenToUse:       []string{"Bump github.com/mbvlabs/andurel/pkg/* already required in go.mod."},
		WhenNotToUse:    []string{"Does not rewrite framework-owned files."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel packages update --dry-run --json", "andurel packages update storage"},
		Mutating:        true,
		RequiresProject: true,
		SupportsDryRun:  true,
	},
	"andurel doctor": {
		Summary:         "Run diagnostic checks on the project",
		WhenToUse:       []string{"Verify health and generated-file drift after changes."},
		WhenNotToUse:    []string{"Doctor is read-only; it does not write generated files."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel doctor --json", "andurel doctor --verbose"},
		RequiresProject: true,
	},
	"andurel commands": {
		Summary:   "Show the command catalog",
		WhenToUse: []string{"Discover commands, flags, and when-to-use metadata."},
		WhenNotToUse: []string{
			"Do not parse human --help when --json is available.",
		},
		Examples: []string{
			"andurel commands --json",
			"andurel commands --markdown",
			"andurel commands --check",
		},
	},
	"andurel inspect project": {
		Summary:         "Inspect project metadata",
		WhenToUse:       []string{"Read lockfile, adapter, and tool status before generating."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect project --json", "andurel inspect project info --json"},
		RequiresProject: true,
	},
	"andurel inspect project info": {
		Summary:         "Show project metadata",
		WhenToUse:       []string{"Same as andurel project; explicit info subcommand."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect project info --json"},
		RequiresProject: true,
	},
	"andurel inspect routes": {
		Summary:         "List the route manifest",
		WhenToUse:       []string{"Inspect URL paths, names, and params."},
		WhenNotToUse:    []string{"Writing resources/js/routes.ts is andurel sync routes."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect routes --json"},
		RequiresProject: true,
	},
	"andurel inspect models": {
		Summary:         "List model files",
		WhenToUse:       []string{"See which models exist before generating another."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect models --json"},
		RequiresProject: true,
	},
	"andurel inspect migrations": {
		Summary:         "List migration files",
		WhenToUse:       []string{"See SQL migrations on disk."},
		WhenNotToUse:    []string{"Applying migrations is andurel db migrate up."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect migrations --json"},
		RequiresProject: true,
	},
	"andurel inspect controllers": {
		Summary:         "List controller files",
		WhenToUse:       []string{"See which controllers exist before generating another."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect controllers --json"},
		RequiresProject: true,
	},
	"andurel inspect views": {
		Summary:         "List Templ view files",
		WhenToUse:       []string{"See which .templ files exist."},
		WhenNotToUse:    []string{"Running templ generate is andurel sync views."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect views --json"},
		RequiresProject: true,
	},
	"andurel inspect jobs": {
		Summary:         "List job and worker files",
		WhenToUse:       []string{"See queue jobs before generating another."},
		WhenNotToUse:    []string{"Creating a job is generate job."},
		Prerequisites:   []string{"Andurel project root"},
		Examples:        []string{"andurel inspect jobs --json"},
		RequiresProject: true,
	},
	"andurel skill": {
		Summary:   "Show or install the embedded Andurel skill",
		WhenToUse: []string{"Arm a coding agent with Andurel layer and CLI rules."},
		Examples:  []string{"andurel skill show", "andurel skill install --harness pi"},
	},
	"andurel skill show": {
		Summary:   "Print the embedded Andurel skill",
		WhenToUse: []string{"Read the skill body without installing it."},
		Examples:  []string{"andurel skill show", "andurel skill show --json"},
	},
	"andurel skill install": {
		Summary:          "Install the embedded skill into an agent harness",
		WhenToUse:        []string{"Copy SKILL.md into .pi, .claude, Codex, OpenCode, or Crush."},
		Prerequisites:    []string{"Andurel project root"},
		Examples:         []string{"andurel skill install --harness pi --json"},
		Mutating:         true,
		RequiresProject:  true,
		SkipDryRunCheck:  true,
		Prompts:          true,
		InteractiveFlags: []string{"--harness"},
	},
}
