package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mbvlabs/andurel/cli/output"
	"github.com/mbvlabs/andurel/layout"
)

func TestRenderPayloadsTSGoldenWidget(t *testing.T) {
	rootDir := setupPayloadsProject(t, "vue")
	writePayloadsController(t, rootDir, "controllers/widgets.go", widgetControllerSource)

	got, count, skipped, err := renderPayloadsTS(rootDir)
	if err != nil {
		t.Fatalf("render payloads: %v", err)
	}
	if count != 5 {
		t.Fatalf("type count = %d, want 5\n%s", count, got)
	}
	if len(skipped) != 0 {
		t.Fatalf("unexpected skipped: %#v", skipped)
	}
	want := "// Code generated by andurel; DO NOT EDIT.\n\n" +
		jsonValueAlias +
		"\nexport type CreateWidgetFormPayload = {\n" +
		"  name: string\n" +
		"  nickname?: string\n" +
		"}\n" +
		"\nexport type UpdateWidgetFormPayload = {\n" +
		"  name: string\n" +
		"}\n" +
		"\nexport type WidgetData = {\n" +
		"  name: string\n" +
		"  metadata: JsonValue\n" +
		"}\n" +
		"\nexport type WidgetIndexProps = {\n" +
		"  items: WidgetData[]\n" +
		"}\n" +
		"\nexport type WidgetItemProps = {\n" +
		"  item: WidgetData\n" +
		"}\n"
	if string(got) != want {
		t.Fatalf("unexpected payloads.ts:\n%s\nwant:\n%s", got, want)
	}
}

func TestRenderPayloadsTSJSONOmitEmbedPointerAndCollision(t *testing.T) {
	rootDir := setupPayloadsProject(t, "react")
	writePayloadsController(t, rootDir, "controllers/pages.go", `package controllers

import (
	"github.com/labstack/echo/v5"
	"github.com/mbvlabs/andurel/pkg/inertia"
)

type BaseData struct {
	Visible string `+"`json:\"visible\"`"+`
	Secret  string `+"`json:\"-\"`"+`
}

type DashboardIndexProps struct {
	BaseData
	Title   string  `+"`json:\"title\"`"+`
	Note    *string `+"`json:\"note\"`"+`
	Nested  struct {
		Count int `+"`json:\"count\"`"+`
	} `+"`json:\"nested\"`"+`
}

func (p Pages) Index(etx *echo.Context) error {
	return inertia.FromStruct(DashboardIndexProps{})
}
`)

	got, _, _, err := renderPayloadsTS(rootDir)
	if err != nil {
		t.Fatalf("render payloads: %v", err)
	}
	for _, want := range []string{
		"export type DashboardIndexProps",
		"visible: string",
		"title: string",
		"note: string | null",
		"nested: { count: number }",
	} {
		if !strings.Contains(string(got), want) {
			t.Fatalf("missing %q in:\n%s", want, got)
		}
	}
	if strings.Contains(string(got), "secret") {
		t.Fatalf("json \"-\" field leaked:\n%s", got)
	}
}

func TestRenderPayloadsTSFailsOnModelsUnmappedGenericsAndBindName(t *testing.T) {
	t.Run("models field", func(t *testing.T) {
		rootDir := setupPayloadsProject(t, "vue")
		writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import (
	"example.com/app/models"
	"github.com/mbvlabs/andurel/pkg/inertia"
	"github.com/labstack/echo/v5"
)

type BadIndexProps struct {
	Item models.Widget `+"`json:\"item\"`"+`
}

func (c Bad) Index(etx *echo.Context) error {
	return inertia.FromStruct(BadIndexProps{})
}
`)
		_, _, _, err := renderPayloadsTS(rootDir)
		if err == nil || !strings.Contains(err.Error(), "define a controller-owned payload type") {
			t.Fatalf("expected models rejection, got %v", err)
		}
	})

	t.Run("unmapped map", func(t *testing.T) {
		rootDir := setupPayloadsProject(t, "vue")
		writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import (
	"github.com/mbvlabs/andurel/pkg/inertia"
	"github.com/labstack/echo/v5"
)

type BadIndexProps struct {
	Values map[string]string `+"`json:\"values\"`"+`
}

func (c Bad) Index(etx *echo.Context) error {
	return inertia.FromStruct(BadIndexProps{})
}
`)
		_, _, _, err := renderPayloadsTS(rootDir)
		if err == nil || !strings.Contains(err.Error(), "unmapped type") {
			t.Fatalf("expected unmapped type rejection, got %v", err)
		}
	})

	t.Run("type parameters", func(t *testing.T) {
		rootDir := setupPayloadsProject(t, "vue")
		writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import (
	"github.com/mbvlabs/andurel/pkg/inertia"
	"github.com/labstack/echo/v5"
)

type PageProps[T any] struct {
	Item T `+"`json:\"item\"`"+`
}

func (c Bad) Index(etx *echo.Context) error {
	return inertia.FromStruct(PageProps[string]{})
}
`)
		_, _, _, err := renderPayloadsTS(rootDir)
		if err == nil {
			t.Fatal("expected type parameter rejection")
		}
	})

	t.Run("bind without Payload suffix", func(t *testing.T) {
		rootDir := setupPayloadsProject(t, "vue")
		writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import "github.com/labstack/echo/v5"

type CreateForm struct {
	Name string `+"`json:\"name\"`"+`
}

func (c Bad) Create(etx *echo.Context) error {
	var payload CreateForm
	return etx.Bind(&payload)
}
`)
		_, _, _, err := renderPayloadsTS(rootDir)
		if err == nil || !strings.Contains(err.Error(), "Payload suffix") {
			t.Fatalf("expected bind rename hint, got %v", err)
		}
	})

	t.Run("name collision", func(t *testing.T) {
		rootDir := setupPayloadsProject(t, "vue")
		writePayloadsController(t, rootDir, "controllers/widgets.go", `package controllers

import (
	"github.com/labstack/echo/v5"
	"github.com/mbvlabs/andurel/pkg/inertia"
)

type WidgetIndexProps struct {
	Title string `+"`json:\"title\"`"+`
}

func (c Widgets) Index(etx *echo.Context) error {
	return inertia.FromStruct(WidgetIndexProps{})
}
`)
		writePayloadsController(t, rootDir, "controllers/admin/widgets.go", `package admin

import (
	"github.com/labstack/echo/v5"
	"github.com/mbvlabs/andurel/pkg/inertia"
)

type WidgetIndexProps struct {
	Title string `+"`json:\"title\"`"+`
}

func (c Widgets) Index(etx *echo.Context) error {
	return inertia.FromStruct(WidgetIndexProps{})
}
`)
		_, _, _, err := renderPayloadsTS(rootDir)
		if err == nil || !strings.Contains(err.Error(), "collision") {
			t.Fatalf("expected collision, got %v", err)
		}
	})
}

func TestRenderPayloadsTSSkipsUnresolvedFromStruct(t *testing.T) {
	rootDir := setupPayloadsProject(t, "vue")
	writePayloadsController(t, rootDir, "controllers/pages.go", `package controllers

import (
	"github.com/labstack/echo/v5"
	"github.com/mbvlabs/andurel/pkg/inertia"
)

func (p Pages) Index(etx *echo.Context) error {
	props := loadProps()
	return inertia.FromStruct(props)
}
`)
	_, count, skipped, err := renderPayloadsTS(rootDir)
	if err != nil {
		t.Fatalf("render payloads: %v", err)
	}
	if count != 0 {
		t.Fatalf("expected no types, got %d", count)
	}
	if len(skipped) != 1 || skipped[0].Reason != "unresolved FromStruct argument" {
		t.Fatalf("unexpected skipped: %#v", skipped)
	}
}

func TestGeneratePayloadsCommandRequiresInertiaProject(t *testing.T) {
	rootDir := setupPayloadsProject(t, "")
	result := runRoutesJSCommandInProject(t, rootDir, "sync", "payloads", "--json")
	if result.err == nil {
		t.Fatal("expected generate payloads to reject non-Inertia project")
	}
	envelope := output.Fail(result.err)
	if envelope.Code != output.CodeInvalidInertiaAdapter {
		t.Fatalf("expected invalid inertia error, got %#v", envelope)
	}
}

func TestGeneratePayloadsCommandWritesFile(t *testing.T) {
	rootDir := setupPayloadsProject(t, "svelte")
	writePayloadsController(t, rootDir, "controllers/widgets.go", widgetControllerSource)

	result := runRoutesJSCommandInProject(t, rootDir, "sync", "payloads", "--json")
	if result.err != nil {
		t.Fatalf("generate payloads failed: %v\n%s", result.err, result.stderr)
	}
	target := filepath.Join(rootDir, generatedPayloadsTSPath)
	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read payloads.ts: %v", err)
	}
	if !strings.Contains(string(got), "export type WidgetIndexProps") {
		t.Fatalf("unexpected payloads.ts:\n%s", got)
	}
	if !strings.Contains(result.stdout, `"generated_file": "resources/js/types/payloads.ts"`) {
		t.Fatalf("expected structured report, got:\n%s", result.stdout)
	}
	if !strings.Contains(result.stdout, `"type_count"`) {
		t.Fatalf("expected type_count, got:\n%s", result.stdout)
	}
}

func TestCodeGenerationChecksSkipsPayloadsTSForNonInertiaProject(t *testing.T) {
	rootDir := setupPayloadsProject(t, "")

	results := codeGenerationChecks(rootDir, false)
	for _, result := range results {
		if result.name == "payloads.ts" {
			t.Fatalf("expected payloads.ts check to be skipped for non-Inertia project: %#v", results)
		}
	}
}

func TestCheckPayloadsTSGeneratePassesWhenCurrent(t *testing.T) {
	rootDir := setupPayloadsProject(t, "react")
	writePayloadsController(t, rootDir, "controllers/widgets.go", widgetControllerSource)
	if _, err := generatePayloadsFile(rootDir); err != nil {
		t.Fatalf("generate payloads.ts: %v", err)
	}

	result := checkPayloadsTSGenerate(rootDir, false)
	if result.status != statusPass {
		t.Fatalf("expected payloads.ts check to pass, got %#v", result)
	}
}

func TestCheckPayloadsTSGenerateFailsWhenMissingOrStale(t *testing.T) {
	rootDir := setupPayloadsProject(t, "vue")
	writePayloadsController(t, rootDir, "controllers/widgets.go", widgetControllerSource)

	missing := checkPayloadsTSGenerate(rootDir, false)
	if missing.status != statusFail || !strings.Contains(missing.message, "missing") {
		t.Fatalf("expected missing payloads.ts failure, got %#v", missing)
	}

	target := filepath.Join(rootDir, generatedPayloadsTSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("create resources/js/types: %v", err)
	}
	if err := os.WriteFile(target, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale payloads.ts: %v", err)
	}

	stale := checkPayloadsTSGenerate(rootDir, false)
	if stale.status != statusFail || !strings.Contains(stale.message, "out of date") {
		t.Fatalf("expected stale payloads.ts failure, got %#v", stale)
	}
	if !strings.Contains(strings.Join(stale.details, "\n"), "andurel sync payloads") {
		t.Fatalf("expected generate payloads hint, got %#v", stale)
	}
}

func TestCheckPayloadsTSGenerateLeavesPerResourceTypeFiles(t *testing.T) {
	rootDir := setupPayloadsProject(t, "svelte")
	writePayloadsController(t, rootDir, "controllers/widgets.go", widgetControllerSource)
	if _, err := generatePayloadsFile(rootDir); err != nil {
		t.Fatalf("generate payloads.ts: %v", err)
	}

	leftover := filepath.Join(rootDir, "resources", "js", "types", "widget.ts")
	want := []byte("export type LegacyWidget = { name: string }\n")
	if err := os.WriteFile(leftover, want, 0o644); err != nil {
		t.Fatalf("write leftover types file: %v", err)
	}

	result := checkPayloadsTSGenerate(rootDir, false)
	if result.status != statusPass {
		t.Fatalf("expected payloads.ts check to pass, got %#v", result)
	}
	got, err := os.ReadFile(leftover)
	if err != nil {
		t.Fatalf("leftover types file missing: %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("doctor mutated leftover per-resource types file:\n%s", got)
	}
}

func TestRefreshInertiaGeneratedTypeScriptFailsOnModels(t *testing.T) {
	rootDir := setupPayloadsProject(t, "vue")
	writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import (
	"example.com/app/models"
	"github.com/mbvlabs/andurel/pkg/inertia"
	"github.com/labstack/echo/v5"
)

type BadIndexProps struct {
	Item models.Widget `+"`json:\"item\"`"+`
}

func (c Bad) Index(etx *echo.Context) error {
	return inertia.FromStruct(BadIndexProps{})
}
`)
	err := refreshInertiaGeneratedTypeScript(rootDir, "vue", false)
	if err == nil {
		t.Fatal("expected models.* to fail inertia generate refresh")
	}
}

func TestRefreshPayloadsTSAfterInertiaGenerationFailsOnModels(t *testing.T) {
	rootDir := setupPayloadsProject(t, "vue")
	writePayloadsController(t, rootDir, "controllers/bad.go", `package controllers

import (
	"example.com/app/models"
	"github.com/mbvlabs/andurel/pkg/inertia"
	"github.com/labstack/echo/v5"
)

type BadIndexProps struct {
	Item models.Widget `+"`json:\"item\"`"+`
}

func (c Bad) Index(etx *echo.Context) error {
	return inertia.FromStruct(BadIndexProps{})
}
`)
	err := refreshPayloadsTSAfterInertiaGeneration(rootDir, "vue", false)
	if err == nil {
		t.Fatal("expected models.* to fail inertia generate refresh")
	}
}

const widgetControllerSource = `package controllers

import (
	"encoding/json"

	"github.com/labstack/echo/v5"
	"github.com/mbvlabs/andurel/pkg/inertia"
)

type WidgetData struct {
	Name     string          ` + "`json:\"name\"`" + `
	Metadata json.RawMessage ` + "`json:\"metadata\"`" + `
}

type WidgetIndexProps struct {
	Items []WidgetData ` + "`json:\"items\"`" + `
}

type WidgetItemProps struct {
	Item WidgetData ` + "`json:\"item\"`" + `
}

type CreateWidgetFormPayload struct {
	Name     string ` + "`json:\"name\"`" + `
	Nickname string ` + "`json:\"nickname,omitempty\"`" + `
}

type UpdateWidgetFormPayload struct {
	Name string ` + "`json:\"name\"`" + `
}

func (c Widgets) Index(etx *echo.Context) error {
	return inertia.FromStruct(WidgetIndexProps{})
}

func (c Widgets) Show(etx *echo.Context) error {
	item := WidgetItemProps{}
	return inertia.FromStruct(item)
}

func (c Widgets) Create(etx *echo.Context) error {
	var payload CreateWidgetFormPayload
	if err := etx.Bind(&payload); err != nil {
		return err
	}
	return nil
}

func (c Widgets) Update(etx *echo.Context) error {
	var payload UpdateWidgetFormPayload
	return etx.Bind(&payload)
}
`

func setupPayloadsProject(t *testing.T, inertia string) string {
	t.Helper()
	rootDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(rootDir, "go.mod"), []byte("module example.com/app\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	lock := layout.AndurelLock{
		SchemaVersion: 1,
		Version:       "test",
		Tools:         map[string]*layout.Tool{},
		ScaffoldConfig: &layout.ScaffoldConfig{
			ProjectName: "app",
			Inertia:     inertia,
		},
		DatabaseConfig: &layout.DatabaseConfig{
			Engine:   layout.DatabaseEnginePostgreSQL,
			NullType: layout.NullTypePGType,
		},
	}
	if err := lock.WriteLockFile(rootDir); err != nil {
		t.Fatalf("write project files: %v", err)
	}
	return rootDir
}

func writePayloadsController(t *testing.T, rootDir, rel, contents string) {
	t.Helper()
	path := filepath.Join(rootDir, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

func TestPayloadsReportJSONShape(t *testing.T) {
	report := payloadsReport{
		GeneratedFile: generatedPayloadsTSPath,
		TypeCount:     2,
		SkippedCount:  1,
		Skipped:       []payloadSkipped{{Reason: "unresolved FromStruct argument", Line: 10}},
	}
	raw, err := json.Marshal(report)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if !bytes.Contains(raw, []byte(`"generated_file"`)) || !bytes.Contains(raw, []byte(`"type_count"`)) ||
		!bytes.Contains(raw, []byte(`"skipped"`)) {
		t.Fatalf("unexpected json: %s", raw)
	}
}
