package cli

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"

	"github.com/mbvlabs/andurel/cli/output"
	"github.com/mbvlabs/andurel/layout"
	"github.com/spf13/cobra"
)

const generatedPayloadsTSPath = "resources/js/types/payloads.ts"

const jsonValueAlias = `export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue }
`

type payloadsReport struct {
	GeneratedFile string           `json:"generated_file"`
	TypeCount     int              `json:"type_count"`
	SkippedCount  int              `json:"skipped_count"`
	Skipped       []payloadSkipped `json:"skipped,omitempty"`
}

type payloadSkipped struct {
	Name       string `json:"name,omitempty"`
	SourceFile string `json:"source_file"`
	Line       int    `json:"line"`
	Reason     string `json:"reason"`
}

type controllerStruct struct {
	name       string
	pkgRel     string
	sourceFile string
	line       int
	structType *ast.StructType
	imports    map[string]string
	typeParams bool
}

type payloadField struct {
	jsonName string
	tsType   string
	optional bool
}

type payloadType struct {
	name   string
	fields []payloadField
}

type payloadScan struct {
	rootDir   string
	fset      *token.FileSet
	structs   map[string]*controllerStruct
	roots     map[string]string
	skipped   []payloadSkipped
	failLater []string
}

func newGeneratePayloadsCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "payloads",
		Short: "Generate TypeScript payload types for Inertia frontends",
		Long: `Generate TypeScript declarations from backend-owned Inertia payload structs.

The command scans controllers for inertia.FromStruct and named Bind payloads
and writes resources/js/types/payloads.ts.`,
		Example: `  andurel generate payloads
  andurel generate payloads --json`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			rootDir, err := findGoModRoot()
			if err != nil {
				return err
			}
			if err := requireInertiaProjectForRoutesJS(rootDir); err != nil {
				return err
			}
			report, err := generatePayloadsFile(rootDir)
			if err != nil {
				return err
			}
			return output.OK(cmd, report, payloadsReportSummary(report))
		},
	}
	setAgentMetadata(
		cmd,
		"generation",
		"Writes Inertia frontend payload types to resources/js/types/payloads.ts from controller structs. Use --json for type and skipped counts.",
	)
	return cmd
}

func payloadsReportSummary(report payloadsReport) string {
	summary := fmt.Sprintf(
		"Generated %d payload types to %s",
		report.TypeCount,
		report.GeneratedFile,
	)
	if report.SkippedCount > 0 {
		summary = fmt.Sprintf("%s (%d skipped)", summary, report.SkippedCount)
	}
	return summary
}

func generatePayloadsFile(rootDir string) (payloadsReport, error) {
	content, typeCount, skipped, err := renderPayloadsTS(rootDir)
	if err != nil {
		return payloadsReport{}, err
	}
	target := filepath.Join(rootDir, generatedPayloadsTSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return payloadsReport{}, err
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		return payloadsReport{}, err
	}
	return payloadsReport{
		GeneratedFile: generatedPayloadsTSPath,
		TypeCount:     typeCount,
		SkippedCount:  len(skipped),
		Skipped:       skipped,
	}, nil
}

func refreshPayloadsTSAfterInertiaGeneration(rootDir, inertia string, isAPI bool) error {
	if isAPI || !layout.IsSupportedInertiaAdapter(inertia) {
		return nil
	}
	_, err := generatePayloadsFile(rootDir)
	return err
}

func renderPayloadsTS(rootDir string) ([]byte, int, []payloadSkipped, error) {
	scan, err := scanControllerPayloads(rootDir)
	if err != nil {
		return nil, 0, nil, err
	}
	emitted, needsJSON, err := scan.emitTypes()
	if err != nil {
		return nil, 0, nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by andurel; DO NOT EDIT.\n")
	if needsJSON {
		buf.WriteString("\n")
		buf.WriteString(jsonValueAlias)
	}
	for _, typ := range emitted {
		buf.WriteString("\nexport type ")
		buf.WriteString(typ.name)
		buf.WriteString(" = {\n")
		for _, field := range typ.fields {
			buf.WriteString("  ")
			if isTypeScriptIdentifier(field.jsonName) {
				buf.WriteString(field.jsonName)
			} else {
				buf.WriteString(strconv.Quote(field.jsonName))
			}
			if field.optional {
				buf.WriteString("?")
			}
			buf.WriteString(": ")
			buf.WriteString(field.tsType)
			buf.WriteString("\n")
		}
		buf.WriteString("}\n")
	}
	return buf.Bytes(), len(emitted), scan.skipped, nil
}

func scanControllerPayloads(rootDir string) (*payloadScan, error) {
	scan := &payloadScan{
		rootDir: rootDir,
		fset:    token.NewFileSet(),
		structs: map[string]*controllerStruct{},
		roots:   map[string]string{},
	}
	if err := walkControllerGoFiles(rootDir, scan.parseControllerFile); err != nil {
		return nil, err
	}
	if err := walkControllerGoFiles(rootDir, scan.discoverInFile); err != nil {
		return nil, err
	}
	return scan, nil
}

func walkControllerGoFiles(rootDir string, visit func(string) error) error {
	controllersDir := filepath.Join(rootDir, "controllers")
	if _, err := os.Stat(controllersDir); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	return filepath.WalkDir(controllersDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if d.Name() == "api" && filepath.Base(filepath.Dir(path)) == "controllers" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		return visit(path)
	})
}

func (s *payloadScan) parseControllerFile(path string) error {
	file, err := parser.ParseFile(s.fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("parse controller file %s: %w", path, err)
	}
	pkgRel := controllerPkgRel(s.rootDir, path)
	imports := controllerImportMap(file)
	sourceFile := routeManifestSourceFile(s.rootDir, path)
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok || !ast.IsExported(typeSpec.Name.Name) {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}
			cs := &controllerStruct{
				name:       typeSpec.Name.Name,
				pkgRel:     pkgRel,
				sourceFile: sourceFile,
				line:       s.fset.Position(typeSpec.Pos()).Line,
				structType: structType,
				imports:    imports,
				typeParams: typeSpec.TypeParams != nil && typeSpec.TypeParams.NumFields() > 0,
			}
			s.structs[structKey(pkgRel, cs.name)] = cs
		}
	}
	return nil
}

func (s *payloadScan) discoverInFile(path string) error {
	file, err := parser.ParseFile(s.fset, path, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("parse controller file %s: %w", path, err)
	}
	pkgRel := controllerPkgRel(s.rootDir, path)
	imports := controllerImportMap(file)
	sourceFile := routeManifestSourceFile(s.rootDir, path)
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Body == nil {
			continue
		}
		locals := collectFuncLocals(fn)
		ast.Inspect(fn.Body, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok || len(call.Args) != 1 {
				return true
			}
			line := s.fset.Position(call.Pos()).Line
			if isInertiaFromStructCall(call.Fun, imports) {
				s.noteFromStruct(call.Args[0], locals, pkgRel, imports, sourceFile, line)
				return true
			}
			if isBindCall(call.Fun) {
				s.noteBind(call.Args[0], locals, pkgRel, imports, sourceFile, line)
			}
			return true
		})
	}
	return nil
}

func (s *payloadScan) noteFromStruct(
	arg ast.Expr,
	locals map[string]ast.Expr,
	pkgRel string,
	imports map[string]string,
	sourceFile string,
	line int,
) {
	pkg, name, ok := s.resolveNamedStruct(arg, locals, pkgRel, imports, map[string]struct{}{})
	if !ok {
		s.skipped = append(s.skipped, payloadSkipped{
			SourceFile: sourceFile,
			Line:       line,
			Reason:     "unresolved FromStruct argument",
		})
		return
	}
	if !ast.IsExported(name) {
		s.skipped = append(s.skipped, payloadSkipped{
			Name: name, SourceFile: sourceFile, Line: line, Reason: "unexported type",
		})
		return
	}
	if isModelsPackage(pkg) {
		s.failLater = append(s.failLater, fmt.Sprintf(
			"%s:%d: FromStruct uses models type %s; define a controller-owned payload type",
			sourceFile, line, name,
		))
		return
	}
	key := structKey(pkg, name)
	if _, exists := s.structs[key]; !exists {
		s.skipped = append(s.skipped, payloadSkipped{
			Name: name, SourceFile: sourceFile, Line: line, Reason: "unresolved FromStruct argument",
		})
		return
	}
	s.roots[key] = "fromstruct"
}

func (s *payloadScan) noteBind(
	arg ast.Expr,
	locals map[string]ast.Expr,
	pkgRel string,
	imports map[string]string,
	sourceFile string,
	line int,
) {
	if ident, ok := pointerIdent(arg); ok {
		if expr, found := locals[ident]; found {
			if isAnonymousStruct(expr) {
				return
			}
			arg = expr
		}
	}
	if isAnonymousStruct(arg) {
		return
	}
	pkg, name, ok := s.resolveNamedStruct(arg, locals, pkgRel, imports, map[string]struct{}{})
	if !ok {
		s.skipped = append(s.skipped, payloadSkipped{
			SourceFile: sourceFile, Line: line, Reason: "unresolved Bind argument",
		})
		return
	}
	if !ast.IsExported(name) {
		s.skipped = append(s.skipped, payloadSkipped{
			Name: name, SourceFile: sourceFile, Line: line, Reason: "unexported type",
		})
		return
	}
	if !strings.HasSuffix(name, "Payload") {
		s.failLater = append(s.failLater, fmt.Sprintf(
			"%s:%d: Bind root %s must be named with a Payload suffix; rename it (for example %sPayload)",
			sourceFile, line, name, name,
		))
		return
	}
	key := structKey(pkg, name)
	if _, exists := s.structs[key]; !exists {
		s.skipped = append(s.skipped, payloadSkipped{
			Name: name, SourceFile: sourceFile, Line: line, Reason: "unresolved Bind argument",
		})
		return
	}
	s.roots[key] = "bind"
}

func (s *payloadScan) emitTypes() ([]payloadType, bool, error) {
	if err := s.firstFailure(); err != nil {
		return nil, false, err
	}
	needed := map[string]*controllerStruct{}
	var add func(*controllerStruct) error
	add = func(cs *controllerStruct) error {
		if cs.typeParams {
			return generationFailed(
				fmt.Sprintf(
					"%s:%d: %s uses type parameters; use a concrete controller-owned struct",
					cs.sourceFile, cs.line, cs.name,
				),
				"Replace the generic struct with a concrete payload type.",
			)
		}
		if existing, ok := needed[cs.name]; ok {
			if existing.pkgRel != cs.pkgRel {
				return generationFailed(
					fmt.Sprintf(
						"payload type name collision for %q: %s and %s",
						cs.name, existing.pkgRel, cs.pkgRel,
					),
					"Rename one of the structs so generated TypeScript names are unique.",
				)
			}
			return nil
		}
		needed[cs.name] = cs
		return s.forNestedStructs(cs, add)
	}

	rootKeys := make([]string, 0, len(s.roots))
	for key := range s.roots {
		rootKeys = append(rootKeys, key)
	}
	slices.Sort(rootKeys)
	for _, key := range rootKeys {
		if err := add(s.structs[key]); err != nil {
			return nil, false, err
		}
	}

	names := make([]string, 0, len(needed))
	for name := range needed {
		names = append(names, name)
	}
	slices.Sort(names)

	emitted := make([]payloadType, 0, len(names))
	needsJSON := false
	for _, name := range names {
		cs := needed[name]
		fields, usedJSON, err := s.mapStructFields(cs, needed)
		if err != nil {
			return nil, false, err
		}
		needsJSON = needsJSON || usedJSON
		emitted = append(emitted, payloadType{name: name, fields: fields})
	}
	return emitted, needsJSON, s.firstFailure()
}

func (s *payloadScan) forNestedStructs(cs *controllerStruct, add func(*controllerStruct) error) error {
	if cs.structType.Fields == nil {
		return nil
	}
	for _, field := range cs.structType.Fields.List {
		for _, ref := range namedStructRefs(field.Type) {
			pkgRel, name, ok := s.lookupRef(cs, ref)
			if !ok {
				continue
			}
			if isModelsPackage(pkgRel) {
				continue
			}
			nested, exists := s.structs[structKey(pkgRel, name)]
			if !exists {
				continue
			}
			if err := add(nested); err != nil {
				return err
			}
		}
	}
	return nil
}

func (s *payloadScan) mapStructFields(
	cs *controllerStruct,
	needed map[string]*controllerStruct,
) ([]payloadField, bool, error) {
	optionalOK := strings.HasSuffix(cs.name, "Payload")
	var fields []payloadField
	needsJSON := false
	if cs.structType.Fields == nil {
		return fields, false, nil
	}
	for _, field := range cs.structType.Fields.List {
		names := field.Names
		anonymous := len(names) == 0
		if anonymous {
			names = []*ast.Ident{{Name: ""}}
		}
		for _, ident := range names {
			if ident.Name != "" && !ast.IsExported(ident.Name) {
				continue
			}
			jsonName, include, omitempty := jsonFieldMeta(field)
			if !include {
				continue
			}
			if anonymous && jsonName == "" {
				embedded := s.embeddedTarget(cs, field.Type, needed)
				nested, usedJSON, err := s.mapStructFields(embedded, needed)
				if err != nil {
					return nil, false, err
				}
				needsJSON = needsJSON || usedJSON
				fields = append(fields, nested...)
				continue
			}
			if jsonName == "" {
				jsonName = ident.Name
			}
			tsType, usedJSON, err := s.mapType(cs, field.Type, field, needed)
			if err != nil {
				return nil, false, err
			}
			needsJSON = needsJSON || usedJSON
			fields = append(fields, payloadField{
				jsonName: jsonName,
				tsType:   tsType,
				optional: optionalOK && omitempty,
			})
		}
	}
	return fields, needsJSON, nil
}

func (s *payloadScan) embeddedTarget(
	cs *controllerStruct,
	expr ast.Expr,
	needed map[string]*controllerStruct,
) *controllerStruct {
	expr = unwrapStar(expr)
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return emptyStruct(cs)
	}
	if nested, ok := needed[ident.Name]; ok {
		return nested
	}
	if nested, ok := s.structs[structKey(cs.pkgRel, ident.Name)]; ok {
		return nested
	}
	return emptyStruct(cs)
}

func emptyStruct(cs *controllerStruct) *controllerStruct {
	return &controllerStruct{
		name:       cs.name,
		pkgRel:     cs.pkgRel,
		sourceFile: cs.sourceFile,
		line:       cs.line,
		structType: &ast.StructType{},
		imports:    cs.imports,
	}
}

func (s *payloadScan) mapType(
	cs *controllerStruct,
	expr ast.Expr,
	field *ast.Field,
	needed map[string]*controllerStruct,
) (string, bool, error) {
	loc := fmt.Sprintf("%s:%d", cs.sourceFile, s.fset.Position(expr.Pos()).Line)
	fieldName := fieldIdent(field)
	switch typed := expr.(type) {
	case *ast.StarExpr:
		inner, usedJSON, err := s.mapType(cs, typed.X, field, needed)
		if err != nil {
			return "", false, err
		}
		return inner + " | null", usedJSON, nil
	case *ast.ArrayType:
		if typed.Len != nil {
			return "", false, unmappedTypeError(loc, fieldName, exprString(expr))
		}
		if ident, ok := typed.Elt.(*ast.Ident); ok && ident.Name == "byte" {
			return "string", false, nil
		}
		inner, usedJSON, err := s.mapType(cs, typed.Elt, field, needed)
		if err != nil {
			return "", false, err
		}
		if strings.Contains(inner, " ") {
			return "(" + inner + ")[]", usedJSON, nil
		}
		return inner + "[]", usedJSON, nil
	case *ast.Ident:
		if mapped, ok := mapBuiltinIdent(typed.Name); ok {
			return mapped, false, nil
		}
		if typed.Name == "any" {
			return "JsonValue", true, nil
		}
		if _, ok := needed[typed.Name]; ok {
			return typed.Name, false, nil
		}
		if _, ok := s.structs[structKey(cs.pkgRel, typed.Name)]; ok {
			return typed.Name, false, nil
		}
		return "", false, unmappedTypeError(loc, fieldName, typed.Name)
	case *ast.SelectorExpr:
		return s.mapSelector(cs, typed, field, loc, fieldName)
	case *ast.InterfaceType:
		if typed.Methods != nil && typed.Methods.NumFields() == 0 {
			return "JsonValue", true, nil
		}
		return "", false, unmappedTypeError(loc, fieldName, exprString(expr))
	case *ast.StructType:
		inline, usedJSON, err := s.mapStructFields(&controllerStruct{
			name:       cs.name,
			pkgRel:     cs.pkgRel,
			sourceFile: cs.sourceFile,
			line:       cs.line,
			structType: typed,
			imports:    cs.imports,
		}, needed)
		if err != nil {
			return "", false, err
		}
		parts := make([]string, 0, len(inline))
		for _, f := range inline {
			name := f.jsonName
			if f.optional {
				name += "?"
			}
			parts = append(parts, name+": "+f.tsType)
		}
		return "{ " + strings.Join(parts, "; ") + " }", usedJSON, nil
	case *ast.IndexExpr, *ast.IndexListExpr:
		return "", false, generationFailed(
			fmt.Sprintf("%s: field %s uses a type parameter or generic instantiation", loc, fieldName),
			"Use a concrete controller-owned payload type.",
		)
	default:
		return "", false, unmappedTypeError(loc, fieldName, exprString(expr))
	}
}

func (s *payloadScan) mapSelector(
	cs *controllerStruct,
	sel *ast.SelectorExpr,
	field *ast.Field,
	loc, fieldName string,
) (string, bool, error) {
	pkgIdent, ok := sel.X.(*ast.Ident)
	if !ok {
		return "", false, unmappedTypeError(loc, fieldName, exprString(sel))
	}
	importPath := cs.imports[pkgIdent.Name]
	if isModelsPackage(importPath) || pkgIdent.Name == "models" {
		return "", false, generationFailed(
			fmt.Sprintf(
				"%s: field %s uses models.%s; define a controller-owned payload type",
				loc, fieldName, sel.Sel.Name,
			),
			"Copy the fields you need onto a controller-owned struct.",
		)
	}
	if mapped, usedJSON, ok := mapKnownSelector(importPath, pkgIdent.Name, sel.Sel.Name); ok {
		return mapped, usedJSON, nil
	}
	rel := controllerPkgFromImport(importPath)
	if _, exists := s.structs[structKey(rel, sel.Sel.Name)]; exists {
		return sel.Sel.Name, false, nil
	}
	return "", false, unmappedTypeError(loc, fieldName, pkgIdent.Name+"."+sel.Sel.Name)
}

func (s *payloadScan) resolveNamedStruct(
	expr ast.Expr,
	locals map[string]ast.Expr,
	pkgRel string,
	imports map[string]string,
	seen map[string]struct{},
) (string, string, bool) {
	expr = unwrapStar(expr)
	switch typed := expr.(type) {
	case *ast.UnaryExpr:
		return s.resolveNamedStruct(typed.X, locals, pkgRel, imports, seen)
	case *ast.CompositeLit:
		return s.resolveNamedStruct(typed.Type, locals, pkgRel, imports, seen)
	case *ast.CallExpr:
		fun, ok := typed.Fun.(*ast.Ident)
		if ok && fun.Name == "new" && len(typed.Args) == 1 {
			return s.resolveNamedStruct(typed.Args[0], locals, pkgRel, imports, seen)
		}
		return "", "", false
	case *ast.IndexExpr:
		return s.resolveNamedStruct(typed.X, locals, pkgRel, imports, seen)
	case *ast.IndexListExpr:
		return s.resolveNamedStruct(typed.X, locals, pkgRel, imports, seen)
	case *ast.Ident:
		if _, loop := seen[typed.Name]; loop {
			return "", "", false
		}
		if local, ok := locals[typed.Name]; ok {
			seen[typed.Name] = struct{}{}
			return s.resolveNamedStruct(local, locals, pkgRel, imports, seen)
		}
		if _, ok := s.structs[structKey(pkgRel, typed.Name)]; ok {
			return pkgRel, typed.Name, true
		}
		return "", "", false
	case *ast.SelectorExpr:
		pkgIdent, ok := typed.X.(*ast.Ident)
		if !ok {
			return "", "", false
		}
		importPath := imports[pkgIdent.Name]
		if isModelsPackage(importPath) || pkgIdent.Name == "models" {
			return "models", typed.Sel.Name, true
		}
		if importPath != "" && !strings.Contains(importPath, "/controllers") &&
			filepath.Base(importPath) != "controllers" {
			return "", "", false
		}
		rel := controllerPkgFromImport(importPath)
		if rel == "" {
			rel = pkgRel
		}
		return rel, typed.Sel.Name, true
	case *ast.ParenExpr:
		return s.resolveNamedStruct(typed.X, locals, pkgRel, imports, seen)
	default:
		return "", "", false
	}
}

func (s *payloadScan) lookupRef(cs *controllerStruct, ref ast.Expr) (string, string, bool) {
	ref = unwrapStar(ref)
	switch typed := ref.(type) {
	case *ast.Ident:
		return cs.pkgRel, typed.Name, true
	case *ast.SelectorExpr:
		pkgIdent, ok := typed.X.(*ast.Ident)
		if !ok {
			return "", "", false
		}
		importPath := cs.imports[pkgIdent.Name]
		if isModelsPackage(importPath) || pkgIdent.Name == "models" {
			return "models", typed.Sel.Name, true
		}
		rel := controllerPkgFromImport(importPath)
		if rel == "" {
			rel = cs.pkgRel
		}
		return rel, typed.Sel.Name, true
	default:
		return "", "", false
	}
}

func (s *payloadScan) firstFailure() error {
	if len(s.failLater) == 0 {
		return nil
	}
	return generationFailed(s.failLater[0], "Fix the controller payload type and run andurel generate payloads.")
}

func generationFailed(message, hint string) error {
	return output.NewError(output.CodeGenerationFailed, message, output.ExitGeneration, hint)
}

func unmappedTypeError(loc, fieldName, typeName string) error {
	return generationFailed(
		fmt.Sprintf("%s: field %s has unmapped type %s; define a controller-owned payload type", loc, fieldName, typeName),
		"Replace the field with a mapped scalar or a named controller struct.",
	)
}

func controllerPkgRel(rootDir, path string) string {
	rel := routeManifestSourceFile(rootDir, filepath.Dir(path))
	if rel == "." || rel == "" {
		return "controllers"
	}
	return rel
}

func structKey(pkgRel, name string) string {
	return pkgRel + "." + name
}

func controllerImportMap(file *ast.File) map[string]string {
	imports := map[string]string{}
	for _, spec := range file.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		name := filepath.Base(path)
		if spec.Name != nil {
			if spec.Name.Name == "_" || spec.Name.Name == "." {
				continue
			}
			name = spec.Name.Name
		}
		imports[name] = path
	}
	return imports
}

func controllerPkgFromImport(importPath string) string {
	if importPath == "" {
		return ""
	}
	idx := strings.Index(importPath, "/controllers")
	if idx == -1 {
		if filepath.Base(importPath) == "controllers" {
			return "controllers"
		}
		return ""
	}
	return strings.TrimPrefix(importPath[idx+1:], "/")
}

func isModelsPackage(pathOrPkg string) bool {
	return pathOrPkg == "models" || strings.HasSuffix(pathOrPkg, "/models")
}

func isInertiaFromStructCall(fun ast.Expr, imports map[string]string) bool {
	sel, ok := fun.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "FromStruct" {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	if !ok {
		return false
	}
	path := imports[ident.Name]
	if path == "" {
		return ident.Name == "inertia"
	}
	return strings.HasSuffix(path, "/inertia") || strings.HasSuffix(path, "/pkg/inertia")
}

func isBindCall(fun ast.Expr) bool {
	sel, ok := fun.(*ast.SelectorExpr)
	return ok && sel.Sel.Name == "Bind"
}

func collectFuncLocals(fn *ast.FuncDecl) map[string]ast.Expr {
	locals := map[string]ast.Expr{}
	ast.Inspect(fn.Body, func(node ast.Node) bool {
		switch typed := node.(type) {
		case *ast.AssignStmt:
			if typed.Tok != token.DEFINE {
				return true
			}
			for i, lhs := range typed.Lhs {
				ident, ok := lhs.(*ast.Ident)
				if !ok || ident.Name == "_" || i >= len(typed.Rhs) {
					continue
				}
				locals[ident.Name] = typed.Rhs[i]
			}
		case *ast.ValueSpec:
			for i, name := range typed.Names {
				if typed.Type != nil {
					locals[name.Name] = typed.Type
					continue
				}
				if i < len(typed.Values) {
					locals[name.Name] = typed.Values[i]
				}
			}
		}
		return true
	})
	return locals
}

func pointerIdent(expr ast.Expr) (string, bool) {
	unary, ok := expr.(*ast.UnaryExpr)
	if !ok {
		return "", false
	}
	ident, ok := unary.X.(*ast.Ident)
	if !ok {
		return "", false
	}
	return ident.Name, true
}

func isAnonymousStruct(expr ast.Expr) bool {
	expr = unwrapStar(expr)
	if unary, ok := expr.(*ast.UnaryExpr); ok {
		expr = unwrapStar(unary.X)
	}
	if lit, ok := expr.(*ast.CompositeLit); ok {
		expr = lit.Type
	}
	_, ok := expr.(*ast.StructType)
	return ok
}

func unwrapStar(expr ast.Expr) ast.Expr {
	for {
		switch typed := expr.(type) {
		case *ast.StarExpr:
			expr = typed.X
		case *ast.ParenExpr:
			expr = typed.X
		default:
			return expr
		}
	}
}

func namedStructRefs(expr ast.Expr) []ast.Expr {
	var refs []ast.Expr
	var walk func(ast.Expr)
	walk = func(e ast.Expr) {
		switch typed := e.(type) {
		case *ast.StarExpr:
			walk(typed.X)
		case *ast.ArrayType:
			walk(typed.Elt)
		case *ast.Ident:
			if ast.IsExported(typed.Name) {
				refs = append(refs, typed)
			}
		case *ast.SelectorExpr:
			refs = append(refs, typed)
		}
	}
	walk(expr)
	return refs
}

func jsonFieldMeta(field *ast.Field) (name string, include bool, omitempty bool) {
	if field.Tag == nil {
		if len(field.Names) == 1 {
			return field.Names[0].Name, true, false
		}
		return "", true, false
	}
	tag, err := strconv.Unquote(field.Tag.Value)
	if err != nil {
		return "", true, false
	}
	jsonTag := reflect.StructTag(tag).Get("json")
	if jsonTag == "" {
		if len(field.Names) == 1 {
			return field.Names[0].Name, true, false
		}
		return "", true, false
	}
	name, opts, _ := strings.Cut(jsonTag, ",")
	if name == "-" {
		return "", false, false
	}
	return name, true, strings.Contains(","+opts+",", ",omitempty,")
}

func fieldIdent(field *ast.Field) string {
	if len(field.Names) == 0 {
		return "(embedded)"
	}
	return field.Names[0].Name
}

func exprString(expr ast.Expr) string {
	switch typed := expr.(type) {
	case *ast.Ident:
		return typed.Name
	case *ast.SelectorExpr:
		return exprString(typed.X) + "." + typed.Sel.Name
	case *ast.StarExpr:
		return "*" + exprString(typed.X)
	case *ast.ArrayType:
		return "[]" + exprString(typed.Elt)
	case *ast.MapType:
		return "map[" + exprString(typed.Key) + "]" + exprString(typed.Value)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func mapBuiltinIdent(name string) (string, bool) {
	switch name {
	case "bool":
		return "boolean", true
	case "string":
		return "string", true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "byte", "rune":
		return "number", true
	default:
		return "", false
	}
}

func mapKnownSelector(importPath, pkgName, typeName string) (string, bool, bool) {
	switch {
	case typeName == "UUID" && (pkgName == "uuid" || strings.HasSuffix(importPath, "uuid")):
		return "string", false, true
	case typeName == "Time" && (pkgName == "time" || strings.HasSuffix(importPath, "time")):
		return "string", false, true
	case typeName == "RawMessage" && (pkgName == "json" || strings.HasSuffix(importPath, "json")):
		return "JsonValue", true, true
	}
	if pkgName == "sql" || strings.HasSuffix(importPath, "database/sql") {
		if mapped, ok := mapSQLNull(typeName); ok {
			return mapped + " | null", false, true
		}
	}
	if pkgName == "pgtype" || strings.HasSuffix(importPath, "pgtype") {
		if mapped, usedJSON, ok := mapPGType(typeName); ok {
			return mapped + " | null", usedJSON, true
		}
	}
	return "", false, false
}

func mapSQLNull(name string) (string, bool) {
	switch name {
	case "NullString":
		return "string", true
	case "NullBool":
		return "boolean", true
	case "NullInt16", "NullInt32", "NullInt64", "NullFloat64", "NullByte":
		return "number", true
	case "NullTime":
		return "string", true
	default:
		return "", false
	}
}

func mapPGType(name string) (string, bool, bool) {
	switch name {
	case "Text":
		return "string", false, true
	case "Bool":
		return "boolean", false, true
	case "Int2", "Int4", "Int8", "Float4", "Float8":
		return "number", false, true
	case "Numeric", "UUID", "Date", "Time", "Timestamp", "Timestamptz", "Bytea":
		return "string", false, true
	case "JSON", "JSONB":
		return "JsonValue", true, true
	default:
		return "", false, false
	}
}
