package cli

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"

	"github.com/mbvlabs/andurel/cli/output"
	"github.com/mbvlabs/andurel/layout"
	"github.com/mbvlabs/andurel/pkg/naming"
	"github.com/spf13/cobra"
)

const generatedRoutesJSPath = "resources/js/routes.ts"

type routesJSReport struct {
	GeneratedFile    string                 `json:"generated_file"`
	GeneratedHelpers int                    `json:"generated_helpers"`
	SkippedCount     int                    `json:"skipped_count"`
	Skipped          []routeManifestSkipped `json:"skipped,omitempty"`
}

type routeJSHelper struct {
	Name  string
	Route routeManifestRoute
}

func newGenerateRoutesCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "routes",
		Short: "Generate TypeScript route helpers for Inertia frontends",
		Long: `Generate framework-neutral TypeScript route helpers for Inertia frontends.

The command reads router/routes/*.go as the source of truth and writes
resources/js/routes.ts for Vue or React Inertia frontends.`,
		Example: `  andurel generate routes
  andurel generate routes --json`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			rootDir, err := findGoModRoot()
			if err != nil {
				return err
			}
			if err := requireInertiaProjectForRoutesJS(rootDir); err != nil {
				return err
			}
			manifest, err := collectRouteManifest(rootDir)
			if err != nil {
				return err
			}
			report, err := generateRoutesJSFile(rootDir, manifest)
			if err != nil {
				return err
			}
			return output.OK(cmd, report, routesJSReportSummary(report))
		},
	}
	setAgentMetadata(cmd, "generation", "Writes Inertia frontend route helpers to resources/js/routes.ts from the route manifest. Use --json for generated helper and skipped counts.")
	return cmd
}

func requireInertiaProjectForRoutesJS(rootDir string) error {
	lock, err := layout.ReadLockFile(rootDir)
	if err != nil {
		return output.WrapError(
			output.CodeConfigError,
			err,
			output.ExitConfig,
			"Run this from an Andurel project with andurel.lock.",
		)
	}
	if lock.ScaffoldConfig == nil || lock.ScaffoldConfig.Inertia == "" {
		return output.NewError(
			output.CodeInvalidInertiaAdapter,
			"andurel generate routes requires an Inertia project",
			output.ExitUsage,
			"Create the project with --inertia vue or --inertia react before generating TypeScript route helpers.",
		)
	}
	if !layout.IsSupportedInertiaAdapter(lock.ScaffoldConfig.Inertia) {
		return output.NewError(
			output.CodeInvalidInertiaAdapter,
			fmt.Sprintf("unsupported inertia adapter in andurel.lock: %s", lock.ScaffoldConfig.Inertia),
			output.ExitUsage,
			"Use vue or react in scaffoldConfig.inertia before generating TypeScript route helpers.",
		)
	}
	return nil
}

func generateRoutesJSFile(rootDir string, manifest routeManifest) (routesJSReport, error) {
	content, helperCount, err := renderRoutesJS(manifest)
	if err != nil {
		return routesJSReport{}, err
	}

	target := filepath.Join(rootDir, generatedRoutesJSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return routesJSReport{}, err
	}
	if err := os.WriteFile(target, content, 0o644); err != nil {
		return routesJSReport{}, err
	}

	return routesJSReport{
		GeneratedFile:    generatedRoutesJSPath,
		GeneratedHelpers: helperCount,
		SkippedCount:     len(manifest.Skipped),
		Skipped:          append([]routeManifestSkipped(nil), manifest.Skipped...),
	}, nil
}

func routesJSReportSummary(report routesJSReport) string {
	summary := fmt.Sprintf("Generated %d route helpers to %s", report.GeneratedHelpers, report.GeneratedFile)
	if report.SkippedCount > 0 {
		summary = fmt.Sprintf("%s (%d skipped)", summary, report.SkippedCount)
	}
	return summary
}

func renderRoutesJS(manifest routeManifest) ([]byte, int, error) {
	helpers, err := routeJSHelpers(manifest.Routes)
	if err != nil {
		return nil, 0, err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by andurel; DO NOT EDIT.\n\n")
	buf.WriteString("export const routes = {\n")
	for _, helper := range helpers {
		line, err := renderRouteJSHelper(helper)
		if err != nil {
			return nil, 0, err
		}
		buf.WriteString("  ")
		buf.WriteString(line)
		buf.WriteString(",\n")
	}
	buf.WriteString("}\n")

	return buf.Bytes(), len(helpers), nil
}

func routeJSHelpers(routes []routeManifestRoute) ([]routeJSHelper, error) {
	helpers := make([]routeJSHelper, 0, len(routes))
	seen := map[string]routeManifestRoute{}
	for _, route := range routes {
		helperName := naming.ToLowerCamelCase(route.Variable)
		if existing, ok := seen[helperName]; ok {
			return nil, output.NewError(
				output.CodeGenerationFailed,
				fmt.Sprintf("route helper name collision for %q: %s and %s both map to %s", helperName, existing.Variable, route.Variable, helperName),
				output.ExitGeneration,
				"Rename one route variable so generated TypeScript helper names are unique.",
			)
		}
		if err := validateRouteJSParams(route); err != nil {
			return nil, err
		}
		seen[helperName] = route
		helpers = append(helpers, routeJSHelper{Name: helperName, Route: route})
	}
	slices.SortStableFunc(helpers, func(a, b routeJSHelper) int {
		return strings.Compare(a.Name, b.Name)
	})
	return helpers, nil
}

func validateRouteJSParams(route routeManifestRoute) error {
	seen := map[string]struct{}{}
	for _, param := range route.Params {
		if !isTypeScriptIdentifier(param.Name) {
			return output.NewError(
				output.CodeGenerationFailed,
				fmt.Sprintf("route %s has parameter %q that cannot be used as a TypeScript identifier", route.Variable, param.Name),
				output.ExitGeneration,
				"Rename the route parameter to a valid identifier before generating TypeScript helpers.",
			)
		}
		if _, ok := seen[param.Name]; ok {
			return output.NewError(
				output.CodeGenerationFailed,
				fmt.Sprintf("route %s repeats parameter %q", route.Variable, param.Name),
				output.ExitGeneration,
				"Use unique parameter names in each route path before generating TypeScript helpers.",
			)
		}
		seen[param.Name] = struct{}{}
	}
	return nil
}

func renderRouteJSHelper(helper routeJSHelper) (string, error) {
	route := helper.Route
	args := make([]string, 0, len(route.Params))
	for _, param := range route.Params {
		args = append(args, fmt.Sprintf("%s: %s", param.Name, routeJSType(param.Type)))
	}

	if len(route.Params) == 0 {
		return fmt.Sprintf("%s: () => '%s'", helper.Name, escapeTSSingleQuoted(route.Path)), nil
	}

	renderedPath, err := renderRouteJSTemplatePath(route)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s: (%s) => `%s`", helper.Name, strings.Join(args, ", "), renderedPath), nil
}

func renderRouteJSTemplatePath(route routeManifestRoute) (string, error) {
	paramSet := map[string]struct{}{}
	for _, param := range route.Params {
		paramSet[param.Name] = struct{}{}
	}

	segments := strings.Split(route.Path, "/")
	for i, segment := range segments {
		if !strings.HasPrefix(segment, ":") {
			segments[i] = escapeTSTemplateStatic(segment)
			continue
		}
		name := strings.TrimPrefix(segment, ":")
		if _, ok := paramSet[name]; !ok {
			return "", output.NewError(
				output.CodeGenerationFailed,
				fmt.Sprintf("route %s path references parameter %q missing from manifest params", route.Variable, name),
				output.ExitGeneration,
				"Inspect the route manifest and route path before generating TypeScript helpers.",
			)
		}
		segments[i] = "${" + name + "}"
	}
	return strings.Join(segments, "/"), nil
}

func routeJSType(manifestType string) string {
	switch manifestType {
	case "int32", "int64":
		return "number"
	case "uuid", "string":
		return "string"
	default:
		return "string"
	}
}

func escapeTSSingleQuoted(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "'", "\\'")
	value = strings.ReplaceAll(value, "\n", "\\n")
	value = strings.ReplaceAll(value, "\r", "\\r")
	return value
}

func escapeTSTemplateStatic(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "`", "\\`")
	value = strings.ReplaceAll(value, "${", "\\${")
	return value
}

func isTypeScriptIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for i, r := range value {
		if i == 0 {
			if r != '_' && r != '$' && !unicode.IsLetter(r) {
				return false
			}
			continue
		}
		if r != '_' && r != '$' && !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}
