package cli

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mbvlabs/andurel/cli/output"
	"github.com/mbvlabs/andurel/layout"
)

func TestRenderRoutesJSGeneratesDeterministicHelpers(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{
				Variable: "WidgetShow",
				Path:     "/widgets/:id",
				Params:   []routeManifestParam{{Name: "id", Type: "uuid"}},
			},
			{
				Variable: "SessionCreate",
				Path:     "/users/sign-in",
			},
			{
				Variable: "DashboardLookup",
				Path:     "/admin/teams/:team_id/dashboards/:dashboard_id",
				Params: []routeManifestParam{
					{Name: "team_id", Type: "int32"},
					{Name: "dashboard_id", Type: "int64"},
				},
			},
			{
				Variable: "PasswordEdit",
				Path:     "/users/password/:token/edit",
				Params:   []routeManifestParam{{Name: "token", Type: "string"}},
			},
			{
				Variable: "ArticleShow",
				Path:     "/articles/:slug",
				Params:   []routeManifestParam{{Name: "slug", Type: "unknown"}},
			},
		},
	}

	got, count, err := renderRoutesJS(manifest)
	if err != nil {
		t.Fatalf("render routes js: %v", err)
	}
	if count != 5 {
		t.Fatalf("expected 5 helpers, got %d", count)
	}

	want := "// Code generated by andurel; DO NOT EDIT.\n\n" +
		"export const routes = {\n" +
		"  articleShow: (slug: string) => `/articles/${slug}`,\n" +
		"  dashboardLookup: (team_id: number, dashboard_id: number) => `/admin/teams/${team_id}/dashboards/${dashboard_id}`,\n" +
		"  passwordEdit: (token: string) => `/users/password/${token}/edit`,\n" +
		"  sessionCreate: () => '/users/sign-in',\n" +
		"  widgetShow: (id: string) => `/widgets/${id}`,\n" +
		"}\n"
	if string(got) != want {
		t.Fatalf("unexpected routes.ts:\n%s", got)
	}
}

func TestRenderRoutesJSEscapesStaticPathSegments(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{
				Variable: "AssetShow",
				Path:     "/assets/it's-$${fine}/:name/`raw`",
				Params:   []routeManifestParam{{Name: "name", Type: "string"}},
			},
			{
				Variable: "QuoteShow",
				Path:     "/quotes/it's-ok",
			},
		},
	}

	got, _, err := renderRoutesJS(manifest)
	if err != nil {
		t.Fatalf("render routes js: %v", err)
	}

	for _, want := range []string{
		"assetShow: (name: string) => `/assets/it's-$\\${fine}/${name}/\\`raw\\``",
		"quoteShow: () => '/quotes/it\\'s-ok'",
	} {
		if !strings.Contains(string(got), want) {
			t.Fatalf("expected output to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderRoutesJSSkipsFrameworkAPIAndAssetRoutes(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{Variable: "Health", Name: "api.health", Path: "/api/health"},
			{Variable: "Robots", Name: "assets.robots", Path: "/robots.txt"},
			{Variable: "Sitemap", Name: "assets.sitemap", Path: "/sitemap.xml"},
			{Variable: "ViteBuild", Name: "vite.build", Path: "/assets/dist/*"},
			{Variable: "SessionNew", Name: "users.new_user_session", Path: "/users/sign-in"},
		},
	}

	got, count, err := renderRoutesJS(manifest)
	if err != nil {
		t.Fatalf("render routes js: %v", err)
	}
	if count != 1 {
		t.Fatalf("expected 1 helper, got %d:\n%s", count, got)
	}
	if !strings.Contains(string(got), "sessionNew: () => '/users/sign-in'") {
		t.Fatalf("expected session route helper, got:\n%s", got)
	}
	for _, unwanted := range []string{"health", "robots", "sitemap", "viteBuild"} {
		if strings.Contains(string(got), unwanted) {
			t.Fatalf("expected generated routes.ts to omit %s, got:\n%s", unwanted, got)
		}
	}
}

func TestRenderRoutesJSDetectsHelperNameCollision(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{Variable: "SessionCreate", Path: "/session"},
			{Variable: "sessionCreate", Path: "/session/new"},
		},
	}

	_, _, err := renderRoutesJS(manifest)
	if err == nil {
		t.Fatal("expected helper name collision error")
	}
	if !strings.Contains(err.Error(), "route helper name collision") {
		t.Fatalf("expected collision error, got %v", err)
	}
}

func TestGenerateRoutesJSFileCreatesDirectoryAndOverwritesFile(t *testing.T) {
	rootDir := t.TempDir()
	target := filepath.Join(rootDir, generatedRoutesJSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("create resources/js: %v", err)
	}
	if err := os.WriteFile(target, []byte("old"), 0o644); err != nil {
		t.Fatalf("write existing routes.ts: %v", err)
	}
	manifest := routeManifest{
		Routes: []routeManifestRoute{{
			Variable: "SessionCreate",
			Path:     "/users/sign-in",
		}},
		Skipped: []routeManifestSkipped{{
			Variable: "DynamicRoute",
			Reason:   "route path is not a static string expression",
		}},
	}

	report, err := generateRoutesJSFile(rootDir, manifest)
	if err != nil {
		t.Fatalf("generate routes: %v", err)
	}
	if report.GeneratedFile != generatedRoutesJSPath || report.GeneratedHelpers != 1 || report.SkippedCount != 1 {
		t.Fatalf("unexpected report: %#v", report)
	}

	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated routes.ts: %v", err)
	}
	if !strings.Contains(string(got), "sessionCreate: () => '/users/sign-in'") {
		t.Fatalf("unexpected generated routes.ts:\n%s", got)
	}
}

func TestGenerateRoutesCommandRequiresInertiaProject(t *testing.T) {
	rootDir := setupRoutesJSCommandProject(t, "")

	result := runRoutesJSCommandInProject(t, rootDir, "generate", "routes", "--json")
	if result.err == nil {
		t.Fatal("expected generate routes to reject non-Inertia project")
	}
	envelope := output.Fail(result.err)
	if envelope.Code != output.CodeInvalidInertiaAdapter {
		t.Fatalf("expected invalid inertia error, got %#v", envelope)
	}
	if _, err := os.Stat(filepath.Join(rootDir, generatedRoutesJSPath)); !os.IsNotExist(err) {
		t.Fatalf("expected routes.ts not to be generated, stat err: %v", err)
	}
}

func TestGenerateRoutesCommandAllowsInertiaProject(t *testing.T) {
	rootDir := setupRoutesJSCommandProject(t, "vue")

	result := runRoutesJSCommandInProject(t, rootDir, "generate", "routes", "--json")
	if result.err != nil {
		t.Fatalf("generate routes failed: %v\nstderr:\n%s", result.err, result.stderr)
	}

	target := filepath.Join(rootDir, generatedRoutesJSPath)
	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated routes.ts: %v", err)
	}
	if !strings.Contains(string(got), "sessionCreate: () => '/users/sign-in'") {
		t.Fatalf("unexpected generated routes.ts:\n%s", got)
	}
	if !strings.Contains(result.stdout, `"generated_file": "resources/js/routes.ts"`) {
		t.Fatalf("expected structured generation report, got:\n%s", result.stdout)
	}
}

func TestCodeGenerationChecksSkipsRoutesTSForNonInertiaProject(t *testing.T) {
	rootDir := setupRoutesJSCommandProject(t, "")

	results := codeGenerationChecks(rootDir, false)
	for _, result := range results {
		if result.name == "routes.ts" {
			t.Fatalf("expected routes.ts check to be skipped for non-Inertia project: %#v", results)
		}
	}
}

func TestCheckRoutesTSGeneratePassesWhenCurrent(t *testing.T) {
	rootDir := setupRoutesJSCommandProject(t, "react")
	manifest, err := collectRouteManifest(rootDir)
	if err != nil {
		t.Fatalf("collect route manifest: %v", err)
	}
	if _, err := generateRoutesJSFile(rootDir, manifest); err != nil {
		t.Fatalf("generate routes.ts: %v", err)
	}

	result := checkRoutesTSGenerate(rootDir, false)
	if result.status != statusPass {
		t.Fatalf("expected routes.ts check to pass, got %#v", result)
	}
}

func TestCheckRoutesTSGenerateFailsWhenMissingOrStale(t *testing.T) {
	rootDir := setupRoutesJSCommandProject(t, "vue")

	missing := checkRoutesTSGenerate(rootDir, false)
	if missing.status != statusFail || !strings.Contains(missing.message, "missing") {
		t.Fatalf("expected missing routes.ts failure, got %#v", missing)
	}

	target := filepath.Join(rootDir, generatedRoutesJSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("create resources/js: %v", err)
	}
	if err := os.WriteFile(target, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale routes.ts: %v", err)
	}

	stale := checkRoutesTSGenerate(rootDir, false)
	if stale.status != statusFail || !strings.Contains(stale.message, "out of date") {
		t.Fatalf("expected stale routes.ts failure, got %#v", stale)
	}
}

func setupRoutesJSCommandProject(t *testing.T, inertia string) string {
	t.Helper()

	rootDir := t.TempDir()
	if err := os.WriteFile(filepath.Join(rootDir, "go.mod"), []byte("module example.com/app\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	lock := layout.AndurelLock{
		SchemaVersion: 1,
		Version:       "test",
		Tools:         map[string]*layout.Tool{},
		ScaffoldConfig: &layout.ScaffoldConfig{
			ProjectName: "app",
			Database:    "postgres",
			Inertia:     inertia,
		},
	}
	lockData, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		t.Fatalf("marshal lock: %v", err)
	}
	lockData = append(lockData, '\n')
	if err := os.WriteFile(filepath.Join(rootDir, "andurel.lock"), lockData, 0o644); err != nil {
		t.Fatalf("write andurel.lock: %v", err)
	}
	writeRouteManifestTestFile(t, rootDir, "users.go", `package routes

import "example.com/app/internal/routing"

const UserPrefix = "/users"

var SessionCreate = routing.NewSimpleRoute(
	"/sign-in",
	"users.user_session",
	UserPrefix,
)
`)
	return rootDir
}

func runRoutesJSCommandInProject(t *testing.T, rootDir string, args ...string) cliTestResult {
	t.Helper()
	resetCLITestSeams(t)
	findGoModRoot = func() (string, error) {
		return rootDir, nil
	}

	var stdout, stderr bytes.Buffer
	cmd := NewRootCommand("test", "test-date")
	cmd.SetOut(&stdout)
	cmd.SetErr(&stderr)
	cmd.SetArgs(args)
	err := cmd.Execute()
	return cliTestResult{
		cmd:    cmd,
		stdout: stdout.String(),
		stderr: stderr.String(),
		err:    err,
	}
}
