package cli

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderRoutesJSGeneratesDeterministicHelpers(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{
				Variable: "WidgetShow",
				Path:     "/widgets/:id",
				Params:   []routeManifestParam{{Name: "id", Type: "uuid"}},
			},
			{
				Variable: "SessionCreate",
				Path:     "/users/sign-in",
			},
			{
				Variable: "DashboardLookup",
				Path:     "/admin/teams/:team_id/dashboards/:dashboard_id",
				Params: []routeManifestParam{
					{Name: "team_id", Type: "int32"},
					{Name: "dashboard_id", Type: "int64"},
				},
			},
			{
				Variable: "PasswordEdit",
				Path:     "/users/password/:token/edit",
				Params:   []routeManifestParam{{Name: "token", Type: "string"}},
			},
			{
				Variable: "ArticleShow",
				Path:     "/articles/:slug",
				Params:   []routeManifestParam{{Name: "slug", Type: "unknown"}},
			},
		},
	}

	got, count, err := renderRoutesJS(manifest)
	if err != nil {
		t.Fatalf("render routes js: %v", err)
	}
	if count != 5 {
		t.Fatalf("expected 5 helpers, got %d", count)
	}

	want := "// Code generated by andurel; DO NOT EDIT.\n\n" +
		"export const routes = {\n" +
		"  articleShow: (slug: string) => `/articles/${slug}`,\n" +
		"  dashboardLookup: (team_id: number, dashboard_id: number) => `/admin/teams/${team_id}/dashboards/${dashboard_id}`,\n" +
		"  passwordEdit: (token: string) => `/users/password/${token}/edit`,\n" +
		"  sessionCreate: () => '/users/sign-in',\n" +
		"  widgetShow: (id: string) => `/widgets/${id}`,\n" +
		"}\n"
	if string(got) != want {
		t.Fatalf("unexpected routes.ts:\n%s", got)
	}
}

func TestRenderRoutesJSEscapesStaticPathSegments(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{
				Variable: "AssetShow",
				Path:     "/assets/it's-$${fine}/:name/`raw`",
				Params:   []routeManifestParam{{Name: "name", Type: "string"}},
			},
			{
				Variable: "QuoteShow",
				Path:     "/quotes/it's-ok",
			},
		},
	}

	got, _, err := renderRoutesJS(manifest)
	if err != nil {
		t.Fatalf("render routes js: %v", err)
	}

	for _, want := range []string{
		"assetShow: (name: string) => `/assets/it's-$\\${fine}/${name}/\\`raw\\``",
		"quoteShow: () => '/quotes/it\\'s-ok'",
	} {
		if !strings.Contains(string(got), want) {
			t.Fatalf("expected output to contain %q, got:\n%s", want, got)
		}
	}
}

func TestRenderRoutesJSDetectsHelperNameCollision(t *testing.T) {
	manifest := routeManifest{
		Routes: []routeManifestRoute{
			{Variable: "SessionCreate", Path: "/session"},
			{Variable: "sessionCreate", Path: "/session/new"},
		},
	}

	_, _, err := renderRoutesJS(manifest)
	if err == nil {
		t.Fatal("expected helper name collision error")
	}
	if !strings.Contains(err.Error(), "route helper name collision") {
		t.Fatalf("expected collision error, got %v", err)
	}
}

func TestGenerateRoutesJSFileCreatesDirectoryAndOverwritesFile(t *testing.T) {
	rootDir := t.TempDir()
	target := filepath.Join(rootDir, generatedRoutesJSPath)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		t.Fatalf("create resources/js: %v", err)
	}
	if err := os.WriteFile(target, []byte("old"), 0o644); err != nil {
		t.Fatalf("write existing routes.ts: %v", err)
	}
	manifest := routeManifest{
		Routes: []routeManifestRoute{{
			Variable: "SessionCreate",
			Path:     "/users/sign-in",
		}},
		Skipped: []routeManifestSkipped{{
			Variable: "DynamicRoute",
			Reason:   "route path is not a static string expression",
		}},
	}

	report, err := generateRoutesJSFile(rootDir, manifest)
	if err != nil {
		t.Fatalf("generate routes: %v", err)
	}
	if report.GeneratedFile != generatedRoutesJSPath || report.GeneratedHelpers != 1 || report.SkippedCount != 1 {
		t.Fatalf("unexpected report: %#v", report)
	}

	got, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("read generated routes.ts: %v", err)
	}
	if !strings.Contains(string(got), "sessionCreate: () => '/users/sign-in'") {
		t.Fatalf("unexpected generated routes.ts:\n%s", got)
	}
}
