// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func CreateInsertUserParams(
	email string,
	name string,
	age pgtype.Int4,
	isActive pgtype.Bool,
) InsertUserParams {
	return InsertUserParams{
		ID:       uuid.New(),
		Email:    email,
		Name:     name,
		Age:      age,
		IsActive: isActive,
	}
}

func CreateUpdateUserParams(
	id uuid.UUID,
	email string,
	name string,
	age pgtype.Int4,
	isActive pgtype.Bool,
) UpdateUserParams {
	return UpdateUserParams{
		ID:       id,
		Email:    email,
		Name:     name,
		Age:      age,
		IsActive: isActive,
	}
}

func CreateQueryPaginatedUsersParams(limit, offset int64) QueryPaginatedUsersParams {
	return QueryPaginatedUsersParams{
		Limit:  limit,
		Offset: offset,
	}
}
