// Code generated by andurel. DO NOT EDIT.
// This file contains constructor functions for SQLC parameters.
// These functions are automatically updated during schema refresh operations.

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

// Constructor functions for SQLC parameters - these get updated during refresh
// to make schema changes compiler-enforced and visible

func NewInsertUserParams(
	email string,
	emailVerifiedAt sql.NullTime,
	password []byte,
	isAdmin int64,
) InsertUserParams {
	return InsertUserParams{
		ID:              uuid.New().String(),
		Email:           email,
		EmailVerifiedAt: emailVerifiedAt,
		Password:        password,
		IsAdmin:         isAdmin,
	}
}

func NewUpdateUserParams(
	id string,
	email string,
	emailVerifiedAt sql.NullTime,
	password []byte,
	isAdmin int64,
) UpdateUserParams {
	return UpdateUserParams{
		ID:              id,
		Email:           email,
		EmailVerifiedAt: emailVerifiedAt,
		Password:        password,
		IsAdmin:         isAdmin,
	}
}

func NewQueryPaginatedUsersParams(limit, offset int64) QueryPaginatedUsersParams {
	return QueryPaginatedUsersParams{
		Limit:  limit,
		Offset: offset,
	}
}
