#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

cd "$repo_root"

go run ./internal/contractgen packages > "$tmp_dir/public-packages.txt"
{
  echo '# Code generated by scripts/update-contracts.sh. DO NOT EDIT.'
  echo '# Public Go API for github.com/mbvlabs/andurel'
  while IFS= read -r package; do
    echo
    echo "## $package"
    go doc -all "$package"
  done < "$tmp_dir/public-packages.txt"
} | sed $'s/\u2014/-/g' > "$tmp_dir/public-api.txt"
go run ./internal/contractgen cli > "$tmp_dir/cli-v1.json"

fixtures=(public-packages.txt cli-v1.json)
if git rev-parse --verify 'v2.0.0^{commit}' >/dev/null 2>&1; then
  fixtures+=(public-api.txt)
else
  echo 'Skipping public-api.txt contract check until v2.0.0 exists' >&2
fi

status=0
for fixture in "${fixtures[@]}"; do
  if ! diff -u "contracts/$fixture" "$tmp_dir/$fixture"; then
    status=1
  fi
done

if (( status != 0 )); then
  echo 'Contract fixtures are stale. Run scripts/update-contracts.sh and review the changes.' >&2
  exit "$status"
fi
