#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

mkdir -p contracts

go run ./internal/contractgen packages > contracts/public-packages.txt

{
  echo '# Code generated by scripts/update-contracts.sh. DO NOT EDIT.'
  echo '# Public Go API for github.com/mbvlabs/andurel'
  while IFS= read -r package; do
    echo
    echo "## $package"
    go doc -all "$package"
  done < contracts/public-packages.txt
} | sed $'s/\u2014/-/g' > contracts/public-api.txt

go run ./internal/contractgen cli > contracts/cli-v1.json
