package upgrade

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/mbvlabs/andurel/layout"
	"github.com/mbvlabs/andurel/layout/templates"
)

func TestPristineRC4CandidatePromotesToStable(t *testing.T) {
	root := t.TempDir()
	mustWriteTestFile(t, root, "go.mod", []byte("module testapp\n\ngo 1.24.0\n"))
	var lock layout.AndurelLock
	if err := json.Unmarshal(mustReadFixture(t, "rc3", "pristine", "andurel.lock"), &lock); err != nil {
		t.Fatal(err)
	}
	lock.Version = "v1.0.0-rc.4"
	lock.SchemaVersion = targetLockSchemaVersion
	lock.ScaffoldConfig.Inertia = "react"
	if lock.DatabaseConfig == nil {
		lock.DatabaseConfig = &layout.DatabaseConfig{NullType: "sql.Null"}
	}
	lockContent, err := marshalLock(&lock)
	if err != nil {
		t.Fatal(err)
	}
	mustWriteTestFile(t, root, "andurel.lock", lockContent)

	rc4Generator := NewTemplateGenerator("v1.0.0-rc.4")
	rendered, err := rc4Generator.RenderFrameworkTemplates(root, *lock.ScaffoldConfig, lock.ExtensionNames())
	if err != nil {
		t.Fatal(err)
	}
	for path, content := range rendered {
		mustWriteTestFile(t, root, path, content)
	}
	data := rc4Generator.buildTemplateData(*lock.ScaffoldConfig, "testapp", lock.ExtensionNames())
	for templateName, path := range map[string]string{
		"config_app.tmpl":    "config/app.go",
		"router_router.tmpl": "router/router.go",
		"models_user.tmpl":   "models/user.go",
		"cmd_app_main.tmpl":  "cmd/app/main.go",
	} {
		content, renderErr := renderTemplateToBytes(templateName, templates.Files, data)
		if renderErr != nil {
			t.Fatal(renderErr)
		}
		mustWriteTestFile(t, root, path, content)
	}
	gitRun(t, root, "init")
	gitRun(t, root, "config", "user.email", "promotion-test@example.com")
	gitRun(t, root, "config", "user.name", "Promotion Test")
	commitUpgradeTree(t, root, "rc4 candidate")

	dry, err := NewUpgrader(root, UpgradeOptions{DryRun: true, TargetVersion: "v1.0.0"})
	if err != nil {
		t.Fatal(err)
	}
	report, err := dry.Execute()
	if err != nil || len(report.Conflicts) != 0 {
		t.Fatalf("RC.4 stable dry run: report=%#v err=%v", report, err)
	}
	stableRendered, err := NewTemplateGenerator("v1.0.0").RenderFrameworkTemplates(root, *lock.ScaffoldConfig, lock.ExtensionNames())
	if err != nil {
		t.Fatal(err)
	}
	for path, rc4Content := range rendered {
		if bytes.Equal(rc4Content, stableRendered[path]) {
			continue
		}
		if !reportContainsReplacement(report, path) {
			t.Fatalf("stable promotion did not recognize banner-only file %s", path)
		}
	}

	real, err := NewUpgrader(root, UpgradeOptions{TargetVersion: "v1.0.0"})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := real.Execute(); err != nil {
		t.Fatal(err)
	}
	updated, err := layout.ReadLockFile(root)
	if err != nil {
		t.Fatal(err)
	}
	if updated.Version != "v1.0.0" {
		t.Fatalf("stable lock version = %s", updated.Version)
	}
}

func reportContainsReplacement(report *UpgradeReport, path string) bool {
	return slices.Contains(report.ReplacedFiles, path)
}

func TestStablePromotionRecognizesOnlyExactSourceAndTargetBanners(t *testing.T) {
	root := t.TempDir()
	path := "internal/server/server.go"
	if err := os.MkdirAll(filepath.Join(root, "internal", "server"), 0o755); err != nil {
		t.Fatal(err)
	}
	rc4 := mustReadFixture(t, "rc4-promotion", "internal", "server", "server.go")
	if got := fmt.Sprintf("%x", sha256.Sum256(rc4)); got != "530cb5e10317ad33e0ecc6f09f096fd70ecf1c9c95b78b296b8c83809350afee" {
		t.Fatalf("RC.4 promotion fixture hash = %s", got)
	}
	target := bytes.Replace(rc4, []byte("v1.0.0-rc.4"), []byte("v1.0.0"), 1)
	tests := []struct {
		name    string
		current string
		want    bool
	}{
		{name: "exact rc4 banner", current: string(rc4), want: true},
		{name: "functional edit", current: "// Code generated by andurel v1.0.0-rc.4; DO NOT EDIT.\npackage changed\n"},
		{name: "mismatched banner", current: "// Code generated by andurel v1.0.0-rc.3; DO NOT EDIT.\npackage server\n"},
		{name: "version in code", current: "// Code generated by andurel v1.0.0-rc.4; DO NOT EDIT.\npackage server\nconst version = \"v1.0.0-rc.4\"\n"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(path)), []byte(test.current), 0o644); err != nil {
				t.Fatal(err)
			}
			got, err := recognizeWholeFileReplacement(root, path, target, "v1.0.0-rc.4", "v1.0.0")
			if err != nil {
				t.Fatal(err)
			}
			if got != test.want {
				t.Fatalf("recognized = %v, want %v", got, test.want)
			}
		})
	}
}
