package upgrade

import (
	"bytes"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/mbvlabs/andurel/layout"
)

const (
	fixtureSourceVersion = "v1.0.3"
	fixtureTargetVersion = "v1.1.0"
)

func TestLockMigrationSelection(t *testing.T) {
	t.Parallel()

	migrations := selectMigrations(MigrationSelector{
		SourceFrameworkVersion: fixtureSourceVersion,
		TargetFrameworkVersion: fixtureTargetVersion,
		SourceLockSchema:       0,
		TargetLockSchema:       targetLockSchemaVersion,
	})
	if len(migrations) != 1 || migrations[0].Name != "lock-schema-legacy-to-1" {
		t.Fatalf("lock migrations = %#v", migrations)
	}
	if migrations := selectMigrations(MigrationSelector{
		SourceFrameworkVersion: fixtureSourceVersion,
		TargetFrameworkVersion: fixtureTargetVersion,
		SourceLockSchema:       1,
		TargetLockSchema:       targetLockSchemaVersion,
	}); len(migrations) != 0 {
		t.Fatalf("current schema migrations = %#v", migrations)
	}
}

func TestUpgraderRemainsComparable(t *testing.T) {
	t.Parallel()

	requireComparable[Upgrader]()
}

func requireComparable[T comparable]() {}

func TestFrameworkFileRecognitionUsesAndurelVersionMarker(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	path := "internal/example/example.go"
	target := []byte("// Code generated by andurel v1.1.0; DO NOT EDIT.\npackage example\n")

	mustWriteTestFile(t, root, path, []byte(
		"// Code generated by andurel v1.0.3; DO NOT EDIT.\npackage example\n\nconst Previous = true\n",
	))
	recognized, err := recognizeWholeFileReplacement(root, path, target)
	if err != nil || !recognized {
		t.Fatalf("versioned replacement recognition = %t, err = %v", recognized, err)
	}

	recognized, err = recognizeWholeFileDeletion(root, path)
	if err != nil || !recognized {
		t.Fatalf("versioned deletion recognition = %t, err = %v", recognized, err)
	}

	mustWriteTestFile(t, root, path, []byte("package example\n\nconst UserOwned = true\n"))
	recognized, err = recognizeWholeFileReplacement(root, path, target)
	if err != nil || recognized {
		t.Fatalf("user-owned replacement recognition = %t, err = %v", recognized, err)
	}

	recognized, err = recognizeWholeFileDeletion(root, path)
	if err != nil || recognized {
		t.Fatalf("user-owned deletion recognition = %t, err = %v", recognized, err)
	}

	missingPath := "internal/example/missing.go"
	recognized, err = recognizeWholeFileReplacement(root, missingPath, target)
	if err != nil || !recognized {
		t.Fatalf("missing versioned replacement recognition = %t, err = %v", recognized, err)
	}
	recognized, err = recognizeWholeFileReplacement(
		root,
		missingPath,
		[]byte("package example\n\nconst UserOwned = true\n"),
	)
	if err != nil || recognized {
		t.Fatalf("missing user-owned replacement recognition = %t, err = %v", recognized, err)
	}
}

func TestUpgradeCleanAndDirtyWorktreeBehavior(t *testing.T) {
	cleanRoot := newUpgradeFixtureProject(t)
	clean, err := NewUpgrader(cleanRoot, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := clean.Execute()
	if err != nil || report.DirtyWorktree {
		t.Fatalf("clean dry run: report=%#v err=%v", report, err)
	}

	dirtyRoot := newUpgradeFixtureProject(t)
	mustWriteTestFile(t, dirtyRoot, "user-edit.txt", []byte("dirty\n"))
	dry, err := NewUpgrader(dirtyRoot, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err = dry.Execute()
	if err != nil || !report.DirtyWorktree {
		t.Fatalf("dirty dry run: report=%#v err=%v", report, err)
	}

	real, err := NewUpgrader(dirtyRoot, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	before := snapshotUpgradeTree(t, dirtyRoot)
	if _, err := real.Execute(); err == nil || !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("dirty real upgrade error = %v", err)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, dirtyRoot))
}

func TestMatchingFrameworkVersionIsImmediateNoOp(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	writeCurrentFixtureLock(t, root)
	mustWriteTestFile(t, root, "dirty.txt", []byte("preserve me\n"))
	before := snapshotUpgradeTree(t, root)

	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	upgrader.transaction = &transactionRuntime{failureInjector: func(operation, _ string) error {
		return errors.New("unexpected transaction operation " + operation)
	}}
	report, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.AlreadyCurrent {
		t.Fatalf("same-version report = %#v", report)
	}
	if report.FilesReplaced != 0 || report.FilesRemoved != 0 || len(report.Diffs) != 0 {
		t.Fatalf("same-version upgrade planned mutations: %#v", report)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestMatchingFrameworkVersionReportsAndRepairsDrift(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	writeCurrentFixtureLock(t, root)
	path := "internal/hypermedia/core.go"
	drift := append(mustReadProjectFile(t, root, path), []byte("\nconst UnexpectedDrift = true\n")...)
	mustWriteTestFile(t, root, path, drift)
	commitUpgradeTree(t, root, "framework drift")
	before := snapshotUpgradeTree(t, root)

	verify, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := verify.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.RepairAvailable || report.RepairApplied || report.AlreadyCurrent {
		t.Fatalf("drift report = %#v", report)
	}
	if !slices.Contains(report.ReplacedFiles, path) {
		t.Fatalf("drifted paths = %v", report.ReplacedFiles)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))

	repair, err := NewUpgrader(root, UpgradeOptions{Repair: true, TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err = repair.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.RepairAvailable || !report.RepairApplied {
		t.Fatalf("repair report = %#v", report)
	}
	if bytes.Contains(mustReadProjectFile(t, root, path), []byte("UnexpectedDrift")) {
		t.Fatal("framework drift was not restored")
	}
}

func TestMatchingFrameworkVersionRejectsDirtyRepair(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	writeCurrentFixtureLock(t, root)
	path := "internal/hypermedia/core.go"
	drift := append(mustReadProjectFile(t, root, path), []byte("\nconst UnexpectedDrift = true\n")...)
	mustWriteTestFile(t, root, path, drift)
	before := snapshotUpgradeTree(t, root)

	repair, err := NewUpgrader(root, UpgradeOptions{Repair: true, TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := repair.Execute()
	if err == nil || !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("dirty repair report=%#v err=%v", report, err)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestDryRunIsDeterministicAndByteReadOnlyOnSameInstance(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	mustWriteTestFile(t, root, "dirty.txt", []byte("preserve me\n"))
	before := snapshotUpgradeTree(t, root)
	statusBefore := gitOutput(t, root, "status", "--porcelain=v1")
	upgrader, err := NewUpgrader(root, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}

	first, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	second, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	firstJSON, _ := json.Marshal(first)
	secondJSON, _ := json.Marshal(second)
	if !bytes.Equal(firstJSON, secondJSON) {
		t.Fatalf("repeated dry runs differ\nfirst: %s\nsecond: %s", firstJSON, secondJSON)
	}
	if !sort.StringsAreSorted(first.ReplacedFiles) || !sort.StringsAreSorted(first.RemovedFiles) {
		t.Fatalf("report paths are not deterministic: %#v", first)
	}
	if len(first.Diffs) == 0 || len(first.LockMigrations) == 0 {
		t.Fatalf("dry-run report is incomplete: %#v", first)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
	if statusAfter := gitOutput(t, root, "status", "--porcelain=v1"); statusAfter != statusBefore {
		t.Fatalf("dry run changed Git state\nbefore: %q\nafter: %q", statusBefore, statusAfter)
	}
}

func TestVersionedFrameworkFilesUpgradeAtomicallyAndIdempotently(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	addCustomToolToLock(t, root)
	commitUpgradeTree(t, root, "custom tool")
	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := upgrader.Execute()
	if err != nil || !report.Success {
		t.Fatalf("upgrade: report=%#v err=%v", report, err)
	}
	assertUpgradeOutcome(t, root)
	commitUpgradeTree(t, root, "upgraded")
	before := snapshotUpgradeTree(t, root)
	second, err := upgrader.Execute()
	if err != nil || !second.Success {
		t.Fatalf("idempotent upgrade: report=%#v err=%v", second, err)
	}
	if second.FilesReplaced != 0 || second.FilesRemoved != 0 || len(second.Diffs) != 0 {
		t.Fatalf("second upgrade was not a no-op: %#v", second)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestInjectedFailuresRollBackByteIdentically(t *testing.T) {
	operations := []string{
		"stage", "validation", "backup", "write", "sync", "close", "rename",
		"directory-sync", "post-write-validation", "cleanup",
	}
	for _, operation := range operations {
		t.Run(operation, func(t *testing.T) {
			root := newUpgradeFixtureProject(t)
			before := snapshotUpgradeTree(t, root)
			upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
			if err != nil {
				t.Fatal(err)
			}
			seen := 0
			upgrader.transaction = &transactionRuntime{failureInjector: func(got, _ string) error {
				if got != operation {
					return nil
				}
				seen++
				if (operation == "write" || operation == "rename" || operation == "directory-sync") && seen == 1 {
					return nil
				}
				return errors.New("injected " + operation)
			}}
			if _, err := upgrader.Execute(); err == nil {
				t.Fatalf("expected injected %s failure", operation)
			}
			assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
		})
	}
}

func TestLockIsReplacedLast(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	var writes []string
	upgrader.transaction = &transactionRuntime{failureInjector: func(operation, path string) error {
		if operation == "write" {
			writes = append(writes, path)
		}
		return nil
	}}
	if _, err := upgrader.Execute(); err != nil {
		t.Fatal(err)
	}
	if len(writes) == 0 || writes[len(writes)-1] != "andurel.lock" {
		t.Fatalf("write order = %v, lock must be last", writes)
	}
}

func newUpgradeFixtureProject(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	mustWriteTestFile(t, root, "go.mod", []byte("module testapp\n\ngo 1.24.0\n"))
	lock := &layout.AndurelLock{
		Version: fixtureSourceVersion,
		Tools:   map[string]*layout.Tool{},
		ScaffoldConfig: &layout.ScaffoldConfig{
			ProjectName: "testapp",
			Database:    "postgresql",
		},
		DatabaseConfig: &layout.DatabaseConfig{NullType: "sql.Null"},
	}
	lockContent, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	var legacyLock map[string]any
	if err := json.Unmarshal(lockContent, &legacyLock); err != nil {
		t.Fatal(err)
	}
	delete(legacyLock, "schemaVersion")
	lockContent, err = json.MarshalIndent(legacyLock, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	mustWriteTestFile(t, root, "andurel.lock", append(lockContent, '\n'))

	rendered, err := NewTemplateGenerator(fixtureSourceVersion).RenderFrameworkTemplates(
		root,
		*lock.ScaffoldConfig,
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	for path, content := range rendered {
		mustWriteTestFile(t, root, path, content)
	}
	mustWriteTestFile(t, root, "internal/application/custom.go", []byte(
		"package application\n\nconst UserOwned = true\n",
	))

	gitRun(t, root, "init")
	gitRun(t, root, "config", "user.email", "upgrade-test@example.com")
	gitRun(t, root, "config", "user.name", "Upgrade Test")
	commitUpgradeTree(t, root, "fixture")
	return root
}

func writeCurrentFixtureLock(t *testing.T, root string) {
	t.Helper()
	lock, err := layout.ReadLockFile(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := lock.WriteLockFile(root); err != nil {
		t.Fatal(err)
	}
	commitUpgradeTree(t, root, "current lock schema")
}

func commitUpgradeTree(t *testing.T, root, message string) {
	t.Helper()
	gitRun(t, root, "add", ".")
	gitRun(t, root, "commit", "-m", message)
}

func gitRun(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
}

func gitOutput(t *testing.T, root string, args ...string) string {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = root
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func mustWriteTestFile(t *testing.T, root, path string, content []byte) {
	t.Helper()
	fullPath := filepath.Join(root, path)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fullPath, content, 0o644); err != nil {
		t.Fatal(err)
	}
}

func mustReadProjectFile(t *testing.T, root, path string) []byte {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(root, path))
	if err != nil {
		t.Fatal(err)
	}
	return content
}

func addCustomToolToLock(t *testing.T, root string) {
	t.Helper()
	var object map[string]any
	if err := json.Unmarshal(mustReadProjectFile(t, root, "andurel.lock"), &object); err != nil {
		t.Fatal(err)
	}
	tools := object["tools"].(map[string]any)
	tools["user-tool"] = map[string]any{
		"version":      "v9.9.9",
		"path":         "cmd/user-tool/main.go",
		"versionCheck": map[string]any{"args": []any{"--version"}},
	}
	content, err := json.MarshalIndent(object, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	mustWriteTestFile(t, root, "andurel.lock", append(content, '\n'))
}

func snapshotUpgradeTree(t *testing.T, root string) map[string][]byte {
	t.Helper()
	result := make(map[string][]byte)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if entry.IsDir() {
			if relative == ".git" || strings.HasPrefix(entry.Name(), ".andurel-upgrade-") {
				return filepath.SkipDir
			}
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		result[filepath.ToSlash(relative)] = content
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func assertSnapshotEqual(t *testing.T, want, got map[string][]byte) {
	t.Helper()
	if !reflect.DeepEqual(want, got) {
		wantPaths := make([]string, 0, len(want))
		gotPaths := make([]string, 0, len(got))
		for path := range want {
			wantPaths = append(wantPaths, path)
		}
		for path := range got {
			gotPaths = append(gotPaths, path)
		}
		sort.Strings(wantPaths)
		sort.Strings(gotPaths)
		t.Fatalf("tree changed\nwant paths: %v\ngot paths: %v", wantPaths, gotPaths)
	}
}

func assertUpgradeOutcome(t *testing.T, root string) {
	t.Helper()
	frameworkFile := mustReadProjectFile(t, root, "internal/hypermedia/core.go")
	if !bytes.Contains(frameworkFile, []byte("andurel "+fixtureTargetVersion)) {
		t.Fatalf("framework file does not contain target version:\n%s", frameworkFile)
	}
	customFile := mustReadProjectFile(t, root, "internal/application/custom.go")
	if !bytes.Contains(customFile, []byte("UserOwned")) {
		t.Fatal("user-owned internal file was changed")
	}
	lock, err := layout.ReadLockFile(root)
	if err != nil {
		t.Fatal(err)
	}
	if lock.SchemaVersion != targetLockSchemaVersion || lock.Version != fixtureTargetVersion {
		t.Fatalf("lock versions = schema %d framework %s", lock.SchemaVersion, lock.Version)
	}
	if _, ok := lock.Tools["user-tool"]; !ok {
		t.Fatal("custom lock tool was not preserved")
	}
}

func TestMigrationRegistryOrderIsStable(t *testing.T) {
	for index := 1; index < len(migrationRegistry); index++ {
		if migrationRegistry[index-1].Order > migrationRegistry[index].Order {
			t.Fatalf("lock migration registry is not ordered at index %d", index)
		}
	}
}
