package upgrade

import (
	"bytes"
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"sort"
	"strings"
	"testing"

	"github.com/mbvlabs/andurel/layout"
)

const (
	fixtureSourceVersion = "v1.0.3"
	fixtureTargetVersion = "v1.1.0"
)

func TestUpgraderRemainsComparable(t *testing.T) {
	t.Parallel()

	requireComparable[Upgrader]()
}

func requireComparable[T comparable]() {}

func TestFrameworkFileRecognitionUsesAndurelVersionMarker(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	path := "internal/example/example.go"
	target := []byte("// Code generated by andurel v1.1.0; DO NOT EDIT.\npackage example\n")

	mustWriteTestFile(t, root, path, []byte(
		"// Code generated by andurel v1.0.3; DO NOT EDIT.\npackage example\n\nconst Previous = true\n",
	))
	recognized, err := recognizeWholeFileReplacement(root, path, target)
	if err != nil || !recognized {
		t.Fatalf("versioned replacement recognition = %t, err = %v", recognized, err)
	}

	recognized, err = recognizeWholeFileDeletion(root, path)
	if err != nil || !recognized {
		t.Fatalf("versioned deletion recognition = %t, err = %v", recognized, err)
	}

	mustWriteTestFile(t, root, path, []byte("package example\n\nconst UserOwned = true\n"))
	recognized, err = recognizeWholeFileReplacement(root, path, target)
	if err != nil || recognized {
		t.Fatalf("user-owned replacement recognition = %t, err = %v", recognized, err)
	}

	recognized, err = recognizeWholeFileDeletion(root, path)
	if err != nil || recognized {
		t.Fatalf("user-owned deletion recognition = %t, err = %v", recognized, err)
	}

	missingPath := "internal/example/missing.go"
	recognized, err = recognizeWholeFileReplacement(root, missingPath, target)
	if err != nil || !recognized {
		t.Fatalf("missing versioned replacement recognition = %t, err = %v", recognized, err)
	}
	recognized, err = recognizeWholeFileReplacement(
		root,
		missingPath,
		[]byte("package example\n\nconst UserOwned = true\n"),
	)
	if err != nil || recognized {
		t.Fatalf("missing user-owned replacement recognition = %t, err = %v", recognized, err)
	}
}

func TestUpgradeCleanAndDirtyWorktreeBehavior(t *testing.T) {
	cleanRoot := newUpgradeFixtureProject(t)
	clean, err := NewUpgrader(cleanRoot, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := clean.Execute()
	if err != nil || report.DirtyWorktree {
		t.Fatalf("clean dry run: report=%#v err=%v", report, err)
	}

	dirtyRoot := newUpgradeFixtureProject(t)
	mustWriteTestFile(t, dirtyRoot, "user-edit.txt", []byte("dirty\n"))
	dry, err := NewUpgrader(dirtyRoot, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err = dry.Execute()
	if err != nil || !report.DirtyWorktree {
		t.Fatalf("dirty dry run: report=%#v err=%v", report, err)
	}

	real, err := NewUpgrader(dirtyRoot, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	before := snapshotUpgradeTree(t, dirtyRoot)
	if _, err := real.Execute(); err == nil || !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("dirty real upgrade error = %v", err)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, dirtyRoot))
}

func TestMatchingFrameworkVersionIsImmediateNoOp(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	mustWriteTestFile(t, root, "dirty.txt", []byte("preserve me\n"))
	before := snapshotUpgradeTree(t, root)

	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	upgrader.transaction = &transactionRuntime{failureInjector: func(operation, _ string) error {
		return errors.New("unexpected transaction operation " + operation)
	}}
	report, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.AlreadyCurrent {
		t.Fatalf("same-version report = %#v", report)
	}
	if report.FilesReplaced != 0 || report.FilesRemoved != 0 || len(report.Diffs) != 0 {
		t.Fatalf("same-version upgrade planned mutations: %#v", report)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestMatchingFrameworkVersionReportsAndRepairsDrift(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	path := "internal/hypermedia/core.go"
	drift := append(mustReadProjectFile(t, root, path), []byte("\nconst UnexpectedDrift = true\n")...)
	mustWriteTestFile(t, root, path, drift)
	commitUpgradeTree(t, root, "framework drift")
	before := snapshotUpgradeTree(t, root)

	verify, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := verify.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.RepairAvailable || report.RepairApplied || report.AlreadyCurrent {
		t.Fatalf("drift report = %#v", report)
	}
	if !slices.Contains(report.ReplacedFiles, path) {
		t.Fatalf("drifted paths = %v", report.ReplacedFiles)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))

	repair, err := NewUpgrader(root, UpgradeOptions{Repair: true, TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err = repair.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !report.Success || !report.RepairAvailable || !report.RepairApplied {
		t.Fatalf("repair report = %#v", report)
	}
	if bytes.Contains(mustReadProjectFile(t, root, path), []byte("UnexpectedDrift")) {
		t.Fatal("framework drift was not restored")
	}
}

func TestMatchingFrameworkVersionRejectsDirtyRepair(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	path := "internal/hypermedia/core.go"
	drift := append(mustReadProjectFile(t, root, path), []byte("\nconst UnexpectedDrift = true\n")...)
	mustWriteTestFile(t, root, path, drift)
	before := snapshotUpgradeTree(t, root)

	repair, err := NewUpgrader(root, UpgradeOptions{Repair: true, TargetVersion: fixtureSourceVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := repair.Execute()
	if err == nil || !strings.Contains(err.Error(), "worktree is dirty") {
		t.Fatalf("dirty repair report=%#v err=%v", report, err)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestDryRunIsDeterministicAndByteReadOnlyOnSameInstance(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	mustWriteTestFile(t, root, "dirty.txt", []byte("preserve me\n"))
	before := snapshotUpgradeTree(t, root)
	statusBefore := gitOutput(t, root, "status", "--porcelain=v1")
	upgrader, err := NewUpgrader(root, UpgradeOptions{DryRun: true, TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}

	first, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	second, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	firstJSON, _ := json.Marshal(first)
	secondJSON, _ := json.Marshal(second)
	if !bytes.Equal(firstJSON, secondJSON) {
		t.Fatalf("repeated dry runs differ\nfirst: %s\nsecond: %s", firstJSON, secondJSON)
	}
	if !sort.StringsAreSorted(first.ReplacedFiles) || !sort.StringsAreSorted(first.RemovedFiles) {
		t.Fatalf("report paths are not deterministic: %#v", first)
	}
	if len(first.Diffs) == 0 {
		t.Fatalf("dry-run report is incomplete: %#v", first)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
	if statusAfter := gitOutput(t, root, "status", "--porcelain=v1"); statusAfter != statusBefore {
		t.Fatalf("dry run changed Git state\nbefore: %q\nafter: %q", statusBefore, statusAfter)
	}
}

func TestSessionRecoveryManualActionDoesNotPlanRouterMutations(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	routerFiles := map[string][]byte{
		"router/cookies/cookies.go":       []byte("package cookies\n\nconst UserOwnedCookies = true\n"),
		"router/cookies/flash.go":         []byte("package cookies\n\nconst UserOwnedFlashes = true\n"),
		"router/middleware/middleware.go": []byte("package middleware\n\nconst UserOwnedMiddleware = true\n"),
	}
	for path, content := range routerFiles {
		mustWriteTestFile(t, root, path, content)
	}
	commitUpgradeTree(t, root, "add user-owned router files")

	upgrader, err := NewUpgrader(root, UpgradeOptions{DryRun: true, TargetVersion: "v1.5.3"})
	if err != nil {
		t.Fatal(err)
	}
	report, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if len(report.ManualActions) != 1 {
		t.Fatalf("manual actions = %#v, want one", report.ManualActions)
	}
	if !strings.Contains(report.ManualActions[0].Instructions, `"testapp/config"`) {
		t.Fatalf("manual action does not use project module:\n%s", report.ManualActions[0].Instructions)
	}
	for _, path := range append(slices.Clone(report.ReplacedFiles), report.RemovedFiles...) {
		if strings.HasPrefix(path, "router/") {
			t.Fatalf("manual action planned router mutation %q", path)
		}
	}
	for path, want := range routerFiles {
		if got := mustReadProjectFile(t, root, path); !bytes.Equal(got, want) {
			t.Fatalf("dry run changed %s:\n%s", path, got)
		}
	}
}

func TestVersionedInertiaUpgradeEmbedsExistingRoot(t *testing.T) {
	root := newUpgradeFixtureProjectWithConfig(t, layout.ScaffoldConfig{
		ProjectName: "testapp",
		Database:    "postgresql",
		Inertia:     "react",
	})
	legacyRoot := []byte("<!doctype html>\n<title>custom root</title>\n{{ .inertia }}\n")
	mustWriteTestFile(t, root, "views/root.go.html", legacyRoot)
	mustWriteTestFile(t, root, "cmd/app/main.go", []byte("package main\n\nfunc main() { inertia.Init(\"views/root.go.html\") }\n"))
	commitUpgradeTree(t, root, "custom inertia root")

	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Contains(report.ReplacedFiles, "assets/inertia/root.go.html") ||
		!slices.Contains(report.ReplacedFiles, "cmd/app/main.go") ||
		!slices.Contains(report.RemovedFiles, "views/root.go.html") {
		t.Fatalf("upgrade did not move embedded root: replaced=%#v removed=%#v", report.ReplacedFiles, report.RemovedFiles)
	}
	if got := mustReadProjectFile(t, root, "assets/inertia/root.go.html"); !bytes.Equal(got, legacyRoot) {
		t.Fatalf("embedded root was not preserved:\n%s", got)
	}
	mainFile := string(mustReadProjectFile(t, root, "cmd/app/main.go"))
	if !strings.Contains(mainFile, `inertia.Init("inertia/root.go.html")`) || strings.Contains(mainFile, `inertia.Init("views/root.go.html")`) {
		t.Fatalf("legacy Inertia initialization was not updated:\n%s", mainFile)
	}
	if _, err := os.Stat(filepath.Join(root, "views/root.go.html")); !os.IsNotExist(err) {
		t.Fatalf("legacy Inertia root still exists: %v", err)
	}
	if lockData := mustReadProjectFile(t, root, "andurel.lock"); bytes.Contains(lockData, []byte("inertiaRoot")) {
		t.Fatalf("upgraded lock contains removed inertiaRoot field:\n%s", lockData)
	}

	renderer := string(mustReadProjectFile(t, root, "internal/inertia/render.go"))
	for _, snippet := range []string{
		`"testapp/assets"`,
		"func Init(rootPath string, opts ...Option) error",
		"assets.Files.ReadFile(rootPath)",
		"gonertia.NewFromBytes(rootHTML, opts...)",
	} {
		if !strings.Contains(renderer, snippet) {
			t.Fatalf("managed inertia renderer missing %q:\n%s", snippet, renderer)
		}
	}
	if strings.Contains(renderer, "andurel.lock") {
		t.Fatalf("managed inertia renderer still reads andurel.lock:\n%s", renderer)
	}
}

func TestVersionedInertiaUpgradeKeepsEmbeddedRoot(t *testing.T) {
	root := newUpgradeFixtureProjectWithConfig(t, layout.ScaffoldConfig{
		ProjectName: "testapp",
		Database:    "postgresql",
		Inertia:     "react",
	})
	embeddedRoot := []byte("already embedded\n")
	mustWriteTestFile(t, root, "assets/inertia/root.go.html", embeddedRoot)
	commitUpgradeTree(t, root, "embedded inertia root")

	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := upgrader.Execute()
	if err != nil {
		t.Fatal(err)
	}
	if slices.Contains(report.ReplacedFiles, "assets/inertia/root.go.html") ||
		slices.Contains(report.ReplacedFiles, "cmd/app/main.go") {
		t.Fatalf("upgrade replaced completed Inertia migration: %#v", report.ReplacedFiles)
	}
	if got := mustReadProjectFile(t, root, "assets/inertia/root.go.html"); !bytes.Equal(got, embeddedRoot) {
		t.Fatalf("embedded root changed:\n%s", got)
	}
}

func TestVersionedInertiaUpgradeRejectsInvalidEmbeddedPath(t *testing.T) {
	root := newUpgradeFixtureProjectWithConfig(t, layout.ScaffoldConfig{
		ProjectName: "testapp",
		Database:    "postgresql",
		Inertia:     "react",
	})
	embeddedDir := filepath.Join(root, "assets", "inertia")
	if err := os.MkdirAll(embeddedDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("root.go.html", filepath.Join(embeddedDir, "root.go.html")); err != nil {
		t.Fatal(err)
	}
	commitUpgradeTree(t, root, "invalid embedded root")

	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := upgrader.Execute(); err == nil || !strings.Contains(err.Error(), "inspect embedded Inertia root") {
		t.Fatalf("upgrade error = %v", err)
	}
}

func TestVersionedInertiaUpgradeRejectsInvalidMigrationState(t *testing.T) {
	tests := []struct {
		name  string
		setup func(*testing.T, string)
		want  string
	}{
		{
			name: "missing legacy root",
			setup: func(t *testing.T, root string) {
				mustWriteTestFile(t, root, "cmd/app/main.go", []byte("package main\n\nfunc main() { inertia.Init(\"views/root.go.html\") }\n"))
			},
			want: "read existing Inertia root",
		},
		{
			name: "missing application entrypoint",
			setup: func(t *testing.T, root string) {
				mustWriteTestFile(t, root, "views/root.go.html", []byte("legacy root\n"))
			},
			want: "read Inertia application entrypoint",
		},
		{
			name: "unknown initialization call",
			setup: func(t *testing.T, root string) {
				mustWriteTestFile(t, root, "views/root.go.html", []byte("legacy root\n"))
				mustWriteTestFile(t, root, "cmd/app/main.go", []byte("package main\n\nfunc main() { inertia.Init(\"custom/root.go.html\") }\n"))
			},
			want: "legacy initialization call not found",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := newUpgradeFixtureProjectWithConfig(t, layout.ScaffoldConfig{
				ProjectName: "testapp",
				Database:    "postgresql",
				Inertia:     "react",
			})
			test.setup(t, root)
			commitUpgradeTree(t, root, test.name)
			before := snapshotUpgradeTree(t, root)

			upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
			if err != nil {
				t.Fatal(err)
			}
			if _, err := upgrader.Execute(); err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("upgrade error = %v, want %q", err, test.want)
			}
			assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
		})
	}
}

func TestVersionedFrameworkFilesUpgradeAtomicallyAndIdempotently(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	addCustomToolToLock(t, root)
	commitUpgradeTree(t, root, "custom tool")
	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	report, err := upgrader.Execute()
	if err != nil || !report.Success {
		t.Fatalf("upgrade: report=%#v err=%v", report, err)
	}
	assertUpgradeOutcome(t, root)
	commitUpgradeTree(t, root, "upgraded")
	before := snapshotUpgradeTree(t, root)
	second, err := upgrader.Execute()
	if err != nil || !second.Success {
		t.Fatalf("idempotent upgrade: report=%#v err=%v", second, err)
	}
	if second.FilesReplaced != 0 || second.FilesRemoved != 0 || len(second.Diffs) != 0 {
		t.Fatalf("second upgrade was not a no-op: %#v", second)
	}
	assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
}

func TestInjectedFailuresRollBackByteIdentically(t *testing.T) {
	operations := []string{
		"stage", "validation", "backup", "write", "sync", "close", "rename",
		"directory-sync", "post-write-validation", "cleanup",
	}
	for _, operation := range operations {
		t.Run(operation, func(t *testing.T) {
			root := newUpgradeFixtureProject(t)
			before := snapshotUpgradeTree(t, root)
			upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
			if err != nil {
				t.Fatal(err)
			}
			seen := 0
			upgrader.transaction = &transactionRuntime{failureInjector: func(got, _ string) error {
				if got != operation {
					return nil
				}
				seen++
				if (operation == "write" || operation == "rename" || operation == "directory-sync") && seen == 1 {
					return nil
				}
				return errors.New("injected " + operation)
			}}
			if _, err := upgrader.Execute(); err == nil {
				t.Fatalf("expected injected %s failure", operation)
			}
			assertSnapshotEqual(t, before, snapshotUpgradeTree(t, root))
		})
	}
}

func TestLockIsReplacedLast(t *testing.T) {
	root := newUpgradeFixtureProject(t)
	upgrader, err := NewUpgrader(root, UpgradeOptions{TargetVersion: fixtureTargetVersion})
	if err != nil {
		t.Fatal(err)
	}
	var writes []string
	upgrader.transaction = &transactionRuntime{failureInjector: func(operation, path string) error {
		if operation == "write" {
			writes = append(writes, path)
		}
		return nil
	}}
	if _, err := upgrader.Execute(); err != nil {
		t.Fatal(err)
	}
	if len(writes) == 0 || writes[len(writes)-1] != "andurel.lock" {
		t.Fatalf("write order = %v, lock must be last", writes)
	}
}

func TestUpgradePlanDeletionBranches(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	path := "internal/example/obsolete.go"
	mustWriteTestFile(t, root, path, []byte("obsolete\n"))

	plan := &upgradePlan{}
	if err := plan.addDeletion(root, path); err != nil {
		t.Fatal(err)
	}
	if len(plan.files) != 1 || !plan.files[0].remove || string(plan.files[0].before) != "obsolete\n" {
		t.Fatalf("deletion plan = %#v", plan.files)
	}
	if err := plan.addDeletion(root, "internal/example/missing.go"); err != nil {
		t.Fatalf("missing deletion should be a no-op: %v", err)
	}
}

func TestFrameworkRecognitionAndPlanningReturnFilesystemErrors(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	path := "internal/example"
	if err := os.MkdirAll(filepath.Join(root, path), 0o755); err != nil {
		t.Fatal(err)
	}

	if _, err := recognizeWholeFileReplacement(root, path, []byte("target")); err == nil {
		t.Fatal("replacement recognition should reject a directory path")
	}
	if _, err := recognizeWholeFileDeletion(root, path); err == nil {
		t.Fatal("deletion recognition should reject a directory path")
	}
	if err := (&upgradePlan{}).addReplacement(root, path, []byte("target"), false); err == nil {
		t.Fatal("replacement planning should reject a directory path")
	}
	if err := (&upgradePlan{}).addDeletion(root, path); err == nil {
		t.Fatal("deletion planning should reject a directory path")
	}
}

func newUpgradeFixtureProject(t *testing.T) string {
	t.Helper()
	return newUpgradeFixtureProjectWithConfig(t, layout.ScaffoldConfig{
		ProjectName: "testapp",
		Database:    "postgresql",
	})
}

func newUpgradeFixtureProjectWithConfig(t *testing.T, config layout.ScaffoldConfig) string {
	t.Helper()
	root := t.TempDir()
	mustWriteTestFile(t, root, "go.mod", []byte("module testapp\n\ngo 1.24.0\n"))
	lock := &layout.AndurelLock{
		SchemaVersion:  targetLockSchemaVersion,
		Version:        fixtureSourceVersion,
		Tools:          map[string]*layout.Tool{},
		ScaffoldConfig: &config,
		DatabaseConfig: &layout.DatabaseConfig{NullType: "sql.Null"},
	}
	lockContent, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	mustWriteTestFile(t, root, "andurel.lock", append(lockContent, '\n'))

	rendered, err := NewTemplateGenerator(fixtureSourceVersion).RenderFrameworkTemplates(
		root,
		*lock.ScaffoldConfig,
		nil,
	)
	if err != nil {
		t.Fatal(err)
	}
	for path, content := range rendered {
		mustWriteTestFile(t, root, path, content)
	}
	mustWriteTestFile(t, root, "internal/application/custom.go", []byte(
		"package application\n\nconst UserOwned = true\n",
	))

	gitRun(t, root, "init")
	gitRun(t, root, "config", "user.email", "upgrade-test@example.com")
	gitRun(t, root, "config", "user.name", "Upgrade Test")
	commitUpgradeTree(t, root, "fixture")
	return root
}

func commitUpgradeTree(t *testing.T, root, message string) {
	t.Helper()
	gitRun(t, root, "add", ".")
	gitRun(t, root, "commit", "-m", message)
}

func gitRun(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
}

func gitOutput(t *testing.T, root string, args ...string) string {
	t.Helper()
	command := exec.Command("git", args...)
	command.Dir = root
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, output)
	}
	return string(output)
}

func mustWriteTestFile(t *testing.T, root, path string, content []byte) {
	t.Helper()
	fullPath := filepath.Join(root, path)
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(fullPath, content, 0o644); err != nil {
		t.Fatal(err)
	}
}

func mustReadProjectFile(t *testing.T, root, path string) []byte {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(root, path))
	if err != nil {
		t.Fatal(err)
	}
	return content
}

func addCustomToolToLock(t *testing.T, root string) {
	t.Helper()
	var object map[string]any
	if err := json.Unmarshal(mustReadProjectFile(t, root, "andurel.lock"), &object); err != nil {
		t.Fatal(err)
	}
	tools := object["tools"].(map[string]any)
	tools["user-tool"] = map[string]any{
		"version":      "v9.9.9",
		"path":         "cmd/user-tool/main.go",
		"versionCheck": map[string]any{"args": []any{"--version"}},
	}
	content, err := json.MarshalIndent(object, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	mustWriteTestFile(t, root, "andurel.lock", append(content, '\n'))
}

func snapshotUpgradeTree(t *testing.T, root string) map[string][]byte {
	t.Helper()
	result := make(map[string][]byte)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if entry.IsDir() {
			if relative == ".git" || strings.HasPrefix(entry.Name(), ".andurel-upgrade-") {
				return filepath.SkipDir
			}
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		result[filepath.ToSlash(relative)] = content
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return result
}

func assertSnapshotEqual(t *testing.T, want, got map[string][]byte) {
	t.Helper()
	if !reflect.DeepEqual(want, got) {
		wantPaths := make([]string, 0, len(want))
		gotPaths := make([]string, 0, len(got))
		for path := range want {
			wantPaths = append(wantPaths, path)
		}
		for path := range got {
			gotPaths = append(gotPaths, path)
		}
		sort.Strings(wantPaths)
		sort.Strings(gotPaths)
		t.Fatalf("tree changed\nwant paths: %v\ngot paths: %v", wantPaths, gotPaths)
	}
}

func assertUpgradeOutcome(t *testing.T, root string) {
	t.Helper()
	frameworkFile := mustReadProjectFile(t, root, "internal/hypermedia/core.go")
	if !bytes.Contains(frameworkFile, []byte("andurel "+fixtureTargetVersion)) {
		t.Fatalf("framework file does not contain target version:\n%s", frameworkFile)
	}
	customFile := mustReadProjectFile(t, root, "internal/application/custom.go")
	if !bytes.Contains(customFile, []byte("UserOwned")) {
		t.Fatal("user-owned internal file was changed")
	}
	lock, err := layout.ReadLockFile(root)
	if err != nil {
		t.Fatal(err)
	}
	if lock.SchemaVersion != targetLockSchemaVersion || lock.Version != fixtureTargetVersion {
		t.Fatalf("lock versions = schema %d framework %s", lock.SchemaVersion, lock.Version)
	}
	if lockData := mustReadProjectFile(t, root, "andurel.lock"); bytes.Contains(lockData, []byte("inertiaRoot")) {
		t.Fatalf("non-Inertia upgrade added inertiaRoot:\n%s", lockData)
	}
	if _, ok := lock.Tools["user-tool"]; !ok {
		t.Fatal("custom lock tool was not preserved")
	}
}
